# Application
spring.application.name=SecureBank
server.port=8080

# H2 Database (file-based - persists between restarts)
spring.datasource.url=jdbc:h2:file:./securebank-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Email (Gmail SMTP) - User must fill in their credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=santoshadkar@gmail.com
spring.mail.password=pzae qcqu pksi ydlp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# Session Timeout (milliseconds) - 3 minutes
app.session.timeout=180000

# Bank Configuration
app.bank.name=SecureBank
app.bank.ifsc=SECB0001234
app.bank.branch=Main Branch
app.bank.branch.code=001234
