// AgileVibe OS - Santoshanand Adkar Coaching Portal Edition

(function() {
  'use strict';

  // -------------------------------------------------------------
  // AUDIO SYNTHESIZER
  // -------------------------------------------------------------
  class SoundFX {
    constructor() {
      this.ctx = null;
      this.muted = false;
    }

    init() {
      if (!this.ctx) {
        const AudioCtx = window.AudioContext || window.webkitAudioContext;
        if (AudioCtx) this.ctx = new AudioCtx();
      }
    }

    playFlip() {
      if (this.muted) return;
      this.init();
      if (!this.ctx) return;
      try {
        const osc = this.ctx.createOscillator();
        const gain = this.ctx.createGain();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(400, this.ctx.currentTime);
        osc.frequency.exponentialRampToValueAtTime(800, this.ctx.currentTime + 0.08);
        gain.gain.setValueAtTime(0.15, this.ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.01, this.ctx.currentTime + 0.08);
        osc.connect(gain);
        gain.connect(this.ctx.destination);
        osc.start();
        osc.stop(this.ctx.currentTime + 0.08);
      } catch (e) {}
    }

    playPop() {
      if (this.muted) return;
      this.init();
      if (!this.ctx) return;
      try {
        const osc = this.ctx.createOscillator();
        const gain = this.ctx.createGain();
        osc.type = 'triangle';
        osc.frequency.setValueAtTime(300, this.ctx.currentTime);
        osc.frequency.exponentialRampToValueAtTime(150, this.ctx.currentTime + 0.05);
        gain.gain.setValueAtTime(0.2, this.ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.01, this.ctx.currentTime + 0.05);
        osc.connect(gain);
        gain.connect(this.ctx.destination);
        osc.start();
        osc.stop(this.ctx.currentTime + 0.05);
      } catch (e) {}
    }

    playChime() {
      if (this.muted) return;
      this.init();
      if (!this.ctx) return;
      try {
        const now = this.ctx.currentTime;
        [523.25, 659.25, 783.99, 1046.50].forEach((freq, i) => {
          const osc = this.ctx.createOscillator();
          const gain = this.ctx.createGain();
          osc.type = 'sine';
          osc.frequency.setValueAtTime(freq, now + i * 0.06);
          gain.gain.setValueAtTime(0.1, now + i * 0.06);
          gain.gain.exponentialRampToValueAtTime(0.001, now + i * 0.06 + 0.3);
          osc.connect(gain);
          gain.connect(this.ctx.destination);
          osc.start(now + i * 0.06);
          osc.stop(now + i * 0.06 + 0.3);
        });
      } catch (e) {}
    }
  }

  const sound = new SoundFX();

  // -------------------------------------------------------------
  // TEMPLATE EXPORTER
  // -------------------------------------------------------------
  class TemplateExporter {
    static downloadFile(content, fileName, contentType) {
      const a = document.createElement('a');
      const file = new Blob([content], { type: contentType });
      a.href = URL.createObjectURL(file);
      a.download = fileName;
      a.click();
      URL.revokeObjectURL(a.href);
    }

    static exportRetroMarkdown(templateName, columns, notes, teamName) {
      let md = `# 🎯 Sprint Retrospective Report - ${teamName}\n`;
      md += `**Coach**: Santoshanand Adkar\n`;
      md += `**Framework**: ${templateName}\n`;
      md += `**Date**: ${new Date().toLocaleDateString()}\n\n---\n\n`;
      columns.forEach(col => {
        const colNotes = notes.filter(n => n.columnId === col.id);
        md += `## ${col.icon} ${col.name}\n`;
        if (colNotes.length === 0) {
          md += `*No notes recorded*\n\n`;
        } else {
          colNotes.forEach(n => { md += `- ${n.text} (❤️ ${n.votes} votes)\n`; });
          md += `\n`;
        }
      });
      md += `---\n*Generated by AgileVibe OS | Santoshanand Adkar*\n`;
      this.downloadFile(md, `Retro_${teamName.replace(/\s+/g, '_')}_${Date.now()}.md`, 'text/markdown');
    }

    static exportRetroJSON(templateName, columns, notes, teamName) {
      const data = { coach: 'Santoshanand Adkar', team: teamName, template: templateName, exportedAt: new Date().toISOString(), columns, notes };
      this.downloadFile(JSON.stringify(data, null, 2), `Retro_${teamName.replace(/\s+/g, '_')}_${Date.now()}.json`, 'application/json');
    }

    static exportExecutivePDF(teamName, maturityScores, psychAnswers, retroNotes) {
      const activeTeamObj = teamName || 'Active Squad';
      const avgScore = (Object.values(maturityScores).reduce((a, b) => a + b, 0) / 5).toFixed(1);
      
      let printWindow = window.open('', '_blank');
      if (!printWindow) {
        alert('Please allow popups to generate the Executive PDF report.');
        return;
      }

      let html = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Executive Coaching Report - ${activeTeamObj} | Santoshanand Adkar</title>
          <style>
            body { font-family: 'Inter', sans-serif; padding: 40px; color: #1e293b; background: #fff; line-height: 1.6; }
            .header { border-bottom: 3px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: center; }
            .header h1 { font-family: 'Outfit', sans-serif; color: #0f172a; margin: 0; font-size: 24px; }
            .badge { background: #6366f1; color: #fff; padding: 6px 14px; border-radius: 20px; font-weight: bold; font-size: 14px; }
            .section { margin-bottom: 24px; }
            .section h2 { color: #4338ca; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; font-size: 18px; margin-bottom: 12px; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
            th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; }
            th { background: #f8fafc; font-weight: 600; color: #475569; }
            .action-item { background: #f1f5f9; padding: 10px 14px; border-left: 4px solid #10b981; margin-bottom: 8px; font-size: 13px; border-radius: 4px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <h1>📊 AgileVibe Executive Summary</h1>
              <div style="font-size: 14px; color: #64748b;">Agile Coach: <strong>Santoshanand Adkar</strong> (santoshadkar@gmail.com)</div>
              <div style="font-size: 13px; color: #64748b; margin-top: 2px;">Squad: <strong>${activeTeamObj}</strong> | Date: ${new Date().toLocaleDateString()}</div>
            </div>
            <div class="badge">Maturity: ${avgScore} / 5.0</div>
          </div>

          <div class="section">
            <h2>🕸️ 1. Agile Maturity Scorecard</h2>
            <table>
              <thead>
                <tr><th>Dimension</th><th>Target</th><th>Current Score</th><th>Assessment Status</th></tr>
              </thead>
              <tbody>
                <tr><td>🌱 Mindset & Culture</td><td>4.0 / 5</td><td>${maturityScores.culture || 4}/5</td><td>${(maturityScores.culture || 4) >= 4 ? '✅ High Performing' : '⚠️ Growth Opportunity'}</td></tr>
                <tr><td>⚡ Technical Excellence</td><td>4.0 / 5</td><td>${maturityScores.technical || 3}/5</td><td>${(maturityScores.technical || 3) >= 4 ? '✅ High Performing' : '⚠️ Growth Opportunity'}</td></tr>
                <tr><td>🎯 Product Alignment</td><td>4.0 / 5</td><td>${maturityScores.product || 4}/5</td><td>${(maturityScores.product || 4) >= 4 ? '✅ High Performing' : '⚠️ Growth Opportunity'}</td></tr>
                <tr><td>🚀 Delivery Speed & Flow</td><td>4.0 / 5</td><td>${maturityScores.delivery || 3}/5</td><td>${(maturityScores.delivery || 3) >= 4 ? '✅ High Performing' : '⚠️ Growth Opportunity'}</td></tr>
                <tr><td>🔄 Continuous Learning</td><td>4.0 / 5</td><td>${maturityScores.improvement || 5}/5</td><td>${(maturityScores.improvement || 5) >= 4 ? '✅ High Performing' : '⚠️ Growth Opportunity'}</td></tr>
              </tbody>
            </table>
          </div>

          <div class="section">
            <h2>🛡️ 2. Team Psychological Safety & Trust Index</h2>
            <div class="action-item" style="border-left-color: #6366f1;">
              <strong>Team Psychological Safety Index:</strong> High Trust Environment. Team members feel safe taking calculated risks and bringing up tough engineering challenges.
            </div>
          </div>

          <div class="section">
            <h2>🎯 3. Agreed Retrospective Action Items</h2>
            ${retroNotes && retroNotes.length > 0 ? retroNotes.slice(0, 5).map(n => `<div class="action-item">🔹 ${n.text} (❤️ ${n.votes} votes)</div>`).join('') : '<div class="action-item">No active retro action items recorded.</div>'}
          </div>

          <div style="margin-top: 40px; font-size: 11px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 16px;">
            Confidential Executive Report | Santoshanand Adkar • santoshadkar@gmail.com
          </div>
        </body>
        </html>
      `;
      printWindow.document.write(html);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 400);
    }
  }

  // -------------------------------------------------------------
  // DEFAULT DATA & SERVICES
  // -------------------------------------------------------------
  const DEFAULT_TEAMS = [
    { id: 'squad-alpha', name: 'Squad Alpha (Mobile & Web)', icon: '🚀' },
    { id: 'squad-beta', name: 'Squad Beta (Core API & Platform)', icon: '⚡' },
    { id: 'squad-gamma', name: 'Squad Gamma (DevSecOps & Data)', icon: '🛡️' }
  ];

  const PRODUCTS_SERVICES_DATA = [
    {
      id: 'enterprise-scaling',
      title: 'Enterprise Agile Transformation & Scaling',
      icon: '🏢',
      desc: 'Custom scaling roadmaps (SAFe, LeSS, Spotify Model) tailored for enterprise engineering orgs of 50 to 1,000+ people.',
      deliverables: ['Value Stream Mapping', 'PI Planning Facilitation', 'Executive Leadership Alignment']
    },
    {
      id: 'role-mentorship',
      title: 'Scrum Master & Product Owner Mentorship',
      icon: '🎓',
      desc: 'Dedicated 1-on-1 coaching bootcamps to elevate Scrum Masters into Master Facilitators and Product Owners into Outcome Owners.',
      deliverables: ['INVEST User Story Workshops', 'GROW/OSKAR Coaching Frameworks', 'Ceremony Observability Audits']
    },
    {
      id: 'psych-safety-audit',
      title: 'Psychological Safety & High-Trust Audits',
      icon: '🛡️',
      desc: 'Diagnostic assessments based on Dr. Amy Edmondson’s research to identify team blame cultures and restore psychological safety.',
      deliverables: ['Team Trust Index Survey', 'Non-Violent Communication Workshops', 'Blameless Post-Mortem Systems']
    },
    {
      id: 'ai-agile-bootcamp',
      title: 'AI-Powered Agile Efficiency Bootcamps',
      icon: '🤖',
      desc: 'Train your engineering teams and Product Owners on how to use AI (Gemini / OpenAI) for story splitting, backlog grooming, and retro synthesis.',
      deliverables: ['Custom AI Prompt Engineering', 'Backlog Auto-Refinement Pipelines', 'AI Coaching Superpower Templates']
    }
  ];

  const CFD_PRESETS = {
    healthy: {
      title: '🟢 Healthy Parallel Flow',
      desc: 'Work moves steadily across all states. Done line slopes upward smoothly and WIP bands remain stable.',
      data: [
        { day: 'Day 1', backlog: 20, dev: 5, review: 2, testing: 1, done: 0 },
        { day: 'Day 2', backlog: 18, dev: 6, review: 3, testing: 1, done: 2 },
        { day: 'Day 3', backlog: 16, dev: 5, review: 4, testing: 2, done: 5 },
        { day: 'Day 4', backlog: 14, dev: 6, review: 3, testing: 2, done: 9 },
        { day: 'Day 5', backlog: 12, dev: 5, review: 4, testing: 3, done: 14 },
        { day: 'Day 6', backlog: 10, dev: 4, review: 3, testing: 2, done: 19 },
        { day: 'Day 7', backlog: 8,  dev: 5, review: 2, testing: 2, done: 23 }
      ]
    }
  };

  const AGILE_COACH_ROLE_DATA = {
    title: 'Who is an Agile Coach & Day in the Life',
    definition: 'An Agile Coach is a catalyst for organizational transformation, team performance, and cultural evolution.',
    stances: [
      { name: 'Teacher', desc: 'Imparting knowledge on Agile frameworks, Scrum, Kanban, and modern DevOps engineering practices.' },
      { name: 'Facilitator', desc: 'Neutral leader of team events, retrospectives, story splitting, and strategic planning sessions.' }
    ],
    dayInTheLife: [
      { time: '08:30 AM - 09:00 AM', title: 'Morning Prep & Flow Scan', desc: 'Inspect Jira/ADO dashboards, review automated test metrics.' }
    ]
  };

  // -------------------------------------------------------------
  // MAIN APP CONTROLLER
  // -------------------------------------------------------------
  class AgileVibeApp {
    constructor() {
      this.currentTab = 'welcome';
      this.teams = JSON.parse(localStorage.getItem('agilevibe_teams') || JSON.stringify(DEFAULT_TEAMS));
      this.activeTeamId = localStorage.getItem('agilevibe_active_team') || 'squad-alpha';
      
      this.activeArticle = null;
      this.selectedPokerCard = null;
      this.cardsRevealed = false;
      this.scalingViewMode = 'table';

      this.teamVotes = [
        { name: 'Sarah (Dev Lead)', card: '5', revealed: false },
        { name: 'Alex (Scrum Master)', card: '8', revealed: false }
      ];

      this.wheelMembers = ['Sarah (Dev)', 'Alex (Scrum Master)', 'Jordan (QA)', 'Taylor (Product)', 'Santoshanand (Coach)'];
      this.wheelAngle = 0;
      this.isSpinning = false;

      this.currentCfdPreset = 'healthy';
      this.cfdData = JSON.parse(JSON.stringify(CFD_PRESETS.healthy.data));

      this.loadActiveTeamState();
    }

    loadActiveTeamState() {
      const savedStateStr = localStorage.getItem(`agilevibe_state_${this.activeTeamId}`);
      if (savedStateStr) {
        try {
          const state = JSON.parse(savedStateStr);
          this.currentRetroTemplate = state.currentRetroTemplate || '4ls';
          this.retroNotes = state.retroNotes || [];
          this.maturityScores = state.maturityScores || { culture: 4, technical: 3, product: 4, delivery: 3, improvement: 5 };
          this.psychAnswers = state.psychAnswers || {};
        } catch (e) {
          this.initDefaultTeamState();
        }
      } else {
        this.initDefaultTeamState();
      }
    }

    initDefaultTeamState() {
      this.currentRetroTemplate = '4ls';
      this.retroNotes = [];
      this.maturityScores = { culture: 4, technical: 3, product: 4, delivery: 3, improvement: 5 };
      this.psychAnswers = {};
    }

    saveActiveTeamState() {
      const state = {
        currentRetroTemplate: this.currentRetroTemplate,
        retroNotes: this.retroNotes,
        maturityScores: this.maturityScores,
        psychAnswers: this.psychAnswers
      };
      localStorage.setItem(`agilevibe_state_${this.activeTeamId}`, JSON.stringify(state));
      localStorage.setItem('agilevibe_active_team', this.activeTeamId);
      localStorage.setItem('agilevibe_teams', JSON.stringify(this.teams));
    }

    switchTeam(teamId) {
      if (teamId === 'add-new-team-trigger') {
        document.getElementById('createTeamModal')?.classList.add('active');
        return;
      }

      this.saveActiveTeamState();
      this.activeTeamId = teamId;
      this.loadActiveTeamState();

      sound.playChime();
      this.renderTeamSelector();
    }

    init() {
      this.setupNavigation();
      this.setupTeamSelector();
      this.setupWelcomeModule();

      document.getElementById('exportExecutivePDFBtn')?.addEventListener('click', () => {
        sound.playChime();
        const activeTeamObj = this.teams.find(t => t.id === this.activeTeamId) || { name: 'Active Squad' };
        TemplateExporter.exportExecutivePDF(activeTeamObj.name, this.maturityScores, this.psychAnswers, this.retroNotes);
      });
    }

    setupWelcomeModule() {
      this.renderProductsServices();

      // Coaching Request Form Submission
      const form = document.getElementById('coachingRequestForm');
      form?.addEventListener('submit', (e) => {
        e.preventDefault();
        sound.playChime();
        const name = document.getElementById('reqName').value;
        const email = document.getElementById('reqEmail').value;
        const service = document.getElementById('reqService').value;

        const resultBox = document.getElementById('requestSuccessBox');
        if (resultBox) {
          resultBox.style.display = 'block';
          resultBox.innerHTML = `
            🎉 <strong>Thank You, ${this.escapeHTML(name)}!</strong><br>
            Your request for <strong>${this.escapeHTML(service)}</strong> has been received by <strong>Santoshanand Adkar</strong>! Santoshanand will contact you at <strong>${this.escapeHTML(email)}</strong> within 24 hours to schedule your discovery call.
          `;
          form.reset();
        }
      });

      // Live Chat Widget Logic
      const chatWidget = document.getElementById('liveChatDrawer');
      document.getElementById('openLiveChatBtn')?.addEventListener('click', () => {
        sound.playPop();
        chatWidget?.classList.add('active');
      });
      document.getElementById('closeLiveChatBtn')?.addEventListener('click', () => {
        sound.playPop();
        chatWidget?.classList.remove('active');
      });

      const chatInput = document.getElementById('chatMsgInput');
      const chatLogs = document.getElementById('chatMessagesLog');
      const sendBtn = document.getElementById('sendChatMsgBtn');

      const handleSendChat = () => {
        const text = chatInput.value.trim();
        if (!text) return;
        sound.playPop();
        chatLogs.innerHTML += `<div class="chat-msg user"><strong>You:</strong> ${this.escapeHTML(text)}</div>`;
        chatInput.value = '';
        chatLogs.scrollTop = chatLogs.scrollHeight;

        setTimeout(() => {
          sound.playChime();
          let reply = 'Hello! I am Santoshanand Adkar’s AI Assistant. Thank you for reaching out! How can Santoshanand assist your team’s delivery flow today?';
          if (text.toLowerCase().includes('price') || text.toLowerCase().includes('cost')) {
            reply = 'Santoshanand offers tailored coaching packages based on squad size and engagement length. Submit a request above or email santoshadkar@gmail.com for a custom quote!';
          } else if (text.toLowerCase().includes('linkedin')) {
            reply = 'You can connect directly with Santoshanand on LinkedIn at https://www.linkedin.com/in/santoshanandadkar/';
          }
          chatLogs.innerHTML += `<div class="chat-msg coach"><strong>Santoshanand's AI Assistant:</strong> ${reply}</div>`;
          chatLogs.scrollTop = chatLogs.scrollHeight;
        }, 600);
      };

      sendBtn?.addEventListener('click', handleSendChat);
      chatInput?.addEventListener('keypress', (e) => { if (e.key === 'Enter') handleSendChat(); });
    }

    renderProductsServices() {
      const container = document.getElementById('servicesCatalogGrid');
      if (!container) return;
      container.innerHTML = PRODUCTS_SERVICES_DATA.map(s => `
        <div class="deep-card" style="padding: 20px;">
          <div style="font-size: 36px; margin-bottom: 8px;">${s.icon}</div>
          <h4 style="font-family: var(--font-heading); font-size: 18px; color: #fff; margin-bottom: 6px;">${s.title}</h4>
          <p style="font-size: 13px; color: var(--text-muted); line-height: 1.5; margin-bottom: 12px;">${s.desc}</p>
          <strong style="font-size: 12px; color: var(--accent-cyan); display: block; margin-bottom: 4px;">KEY DELIVERABLES:</strong>
          <ul style="list-style: none; font-size: 12px; color: #cbd5e1;">
            ${s.deliverables.map(d => `<li>🔹 ${d}</li>`).join('')}
          </ul>
        </div>
      `).join('');
    }

    setupTeamSelector() {
      const selector = document.getElementById('teamSelector');
      if (selector) {
        selector.addEventListener('change', (e) => {
          this.switchTeam(e.target.value);
        });
      }
    }

    renderTeamSelector() {
      const selector = document.getElementById('teamSelector');
      if (!selector) return;
      selector.innerHTML = `
        ${this.teams.map(t => `<option value="${t.id}" ${t.id === this.activeTeamId ? 'selected' : ''}>${t.name}</option>`).join('')}
        <option value="add-new-team-trigger">➕ Add New Squad...</option>
      `;
    }

    setupNavigation() {
      const navItems = document.querySelectorAll('.nav-item');
      navItems.forEach(item => {
        item.addEventListener('click', () => {
          const tabId = item.dataset.tab;
          if (!tabId) return;
          sound.playPop();
          navItems.forEach(n => n.classList.remove('active'));
          item.classList.add('active');

          document.querySelectorAll('.tab-panel').forEach(panel => panel.classList.remove('active'));
          const activePanel = document.getElementById(`panel-${tabId}`);
          if (activePanel) {
            activePanel.classList.add('active');
            this.currentTab = tabId;
          }
        });
      });
    }

    escapeHTML(str) {
      return (str || '').replace(/[&<>'"]/g, tag => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[tag] || tag));
    }
  }

  document.addEventListener('DOMContentLoaded', () => {
    const app = new AgileVibeApp();
    app.init();
  });
})();
