// AgileVibe OS - Universal Template Exporter & Report Generator

export class TemplateExporter {
  static downloadFile(content, fileName, contentType) {
    const a = document.createElement('a');
    const file = new Blob([content], { type: contentType });
    a.href = URL.createObjectURL(file);
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  static exportRetroMarkdown(templateName, columns, notes) {
    let md = `# 🎯 Sprint Retrospective Report\n`;
    md += `**Framework**: ${templateName}\n`;
    md += `**Date**: ${new Date().toLocaleDateString()}\n\n`;
    md += `---\n\n`;

    columns.forEach(col => {
      const colNotes = notes.filter(n => n.columnId === col.id);
      md += `## ${col.icon} ${col.name}\n`;
      if (colNotes.length === 0) {
        md += `*No notes recorded*\n\n`;
      } else {
        colNotes.forEach(n => {
          md += `- ${n.text} (❤️ ${n.votes} votes)\n`;
        });
        md += `\n`;
      }
    });

    md += `---\n*Generated by AgileVibe OS - Central Agile Coaching Portal*\n`;
    this.downloadFile(md, `Retro_${templateName.replace(/\s+/g, '_')}_${Date.now()}.md`, 'text/markdown');
  }

  static exportRetroJSON(templateName, columns, notes) {
    const data = {
      template: templateName,
      exportedAt: new Date().toISOString(),
      columns,
      notes
    };
    this.downloadFile(JSON.stringify(data, null, 2), `Retro_${Date.now()}.json`, 'application/json');
  }

  static exportAssessmentReport(title, scores, recommendations) {
    let md = `# 📊 ${title} Executive Report\n`;
    md += `**Date**: ${new Date().toLocaleDateString()}\n\n`;
    md += `## Assessment Scores\n`;

    Object.entries(scores).forEach(([key, val]) => {
      md += `- **${key.toUpperCase()}**: ${val} / 5\n`;
    });

    md += `\n## Key Coaching Recommendations\n`;
    md += `${recommendations}\n\n`;
    md += `---\n*Generated by AgileVibe OS*\n`;

    this.downloadFile(md, `${title.replace(/\s+/g, '_')}_Report.md`, 'text/markdown');
  }

  static exportArticleMarkdown(title, category, content) {
    let md = `# 📖 ${title}\n`;
    md += `**Category**: ${category}\n`;
    md += `**Exported**: ${new Date().toLocaleDateString()}\n\n`;
    md += `---\n\n`;
    md += content;
    md += `\n\n---\n*Generated by AgileVibe OS Coaching Library*\n`;

    this.downloadFile(md, `${title.replace(/\s+/g, '_')}_Guide.md`, 'text/markdown');
  }
}
