import os

BASE_DIR = r"C:\Users\anany\.gemini\antigravity\scratch\agile_ai_coaching_book"
PART8_DIR = os.path.join(BASE_DIR, "chapters", "part8_hands_on_ai")

ch27_content = """# Chapter 27: Atlassian Rovo Masterclass: Jira Cloud AI Agents & Forge Extensions

## 27.1 Atlassian Rovo Architecture: Search, Chat, and Custom Agents
### Strategic Alignment & Organizational Context
Atlassian Rovo introduces native, enterprise-grade AI capabilities deeply integrated into Jira Cloud, Confluence, and Jira Service Management. Built on top of the Atlassian Teamwork Graph, Rovo connects organizational knowledge, team activity, and third-party tools (GitHub, Google Drive, Figma, Slack) into a unified context layer.

### Architectural Design & System Mechanics
Rovo operates across three core modalities:
1. **Rovo Search**: Enterprise semantic search synthesizing results across Jira, Confluence, Google Drive, and GitHub.
2. **Rovo Chat**: Context-aware conversational AI assistant embedded directly inside Jira Cloud issues and Confluence pages.
3. **Rovo Agents**: Specialized AI agents configured with custom prompt logic, permissions, and Atlassian Forge action modules.

```yaml
# Atlassian Forge Manifest (manifest.yml): Registering a Custom Rovo Agent Action
manifestVersion: 1.0
app:
  id: ari:cloud:ecosystem::app/ee72a5b8-rovo-agent-custom
  name: Enterprise Backlog Refinement Rovo Agent
modules:
  rovo:agent:
    - key: backlog-refinement-agent
      name: Backlog Refinement Co-Pilot
      description: Automates INVEST criteria validation and BDD generation in Jira Cloud
      prompt: >
        You are a specialized Agile Backlog Refinement Agent. Analyze Jira issues,
        verify INVEST criteria, and invoke the BDD Criteria Generator tool.
      actions:
        - add-bdd-criteria-action

  action:
    - key: add-bdd-criteria-action
      name: Add BDD Acceptance Criteria to Issue
      description: Writes generated GIVEN/WHEN/THEN criteria to Jira issue description
      function: main-action-function
      inputs:
        issueKey:
          title: Issue Key
          type: string
          required: true
        bddText:
          title: BDD Criteria Text
          type: string
          required: true

  function:
    - key: main-action-function
      handler: index.runAction

permissions:
  scopes:
    - read:jira-work
    - write:jira-work
```

```javascript
// Forge Serverless Action Handler (index.js)
import api, { route } from "@atlassian/forge-api";

export async function runAction(event) {
  const { issueKey, bddText } = event.inputs;
  
  // Fetch current issue description
  const response = await api.asApp().requestJira(route`/rest/api/3/issue/${issueKey}`);
  const issueData = await response.json();
  
  // Append generated BDD text
  const updatedDescription = `${issueData.fields.description}\n\n*Acceptance Criteria (Generated by Rovo Agent):*\n${bddText}`;
  
  await api.asApp().requestJira(route`/rest/api/3/issue/${issueKey}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      fields: { description: updatedDescription }
    })
  });
  
  return { success: true, message: `Successfully updated ${issueKey} with BDD criteria.` };
}
```

### Quantitative Benchmarks & Operational Metrics
| Rovo Modality | Context Source | Security Boundary | Execution Runtime |
| :--- | :--- | :--- | :--- |
| Rovo Search | Atlassian Teamwork Graph | User Permission Enforced | Search Index |
| Rovo Chat | Page/Issue Context Window | User Permission Enforced | Atlassian Cloud |
| Custom Rovo Agent | Teamwork Graph + Forge Actions | App Manifest Scopes | Forge Serverless FaaS |

### Step-by-Step Enterprise Execution Blueprint
1. **Enable Rovo Services**: Activate Atlassian Rovo in Organization Admin Hub and configure permissions.
2. **Connect Enterprise Connectors**: Bind Google Drive, GitHub, and Figma repositories into Rovo Search.
3. **Configure Custom Rovo Agent**: Define agent prompt instructions, operational persona, and target Jira projects.
4. **Develop Forge Action Module**: Implement serverless Node.js actions in Atlassian Forge (`manifest.yml`).
5. **Audit Agent Permissions**: Verify that Rovo Agents strictly respect user ACLs and Atlassian Access security policies.

### Real-World Enterprise Case Study
A global SaaS company with 400 developers deployed custom Atlassian Rovo Agents in Jira Cloud. When bugs were filed, Rovo Agents automatically queried connected GitHub repositories, identified relevant pull requests, generated BDD test cases, and assigned tickets to appropriate squads. This reduced triage duration from **4 hours to 8 minutes** per ticket.

### Enterprise Agile Coaching Playbook
- *How does our team's operational practice in **Atlassian Rovo** ensure Rovo Agents respect user access permissions?*
- *What Forge manifest permissions are required to allow Rovo Agents to update Jira issue fields safely?*
- *How do we measure the impact of Rovo Search on reducing developer context switching across tools?*

---

---

## 27.7 Chapter 27 Executive Summary
- **Key Takeaway**: Atlassian Rovo integrates native AI capabilities into Jira Cloud via Rovo Search, Rovo Chat, and custom Rovo Agents powered by the Teamwork Graph.
- **Key Takeaway**: Custom Rovo Agents can be extended with Atlassian Forge serverless action modules to perform automated issue updates, BDD additions, and triaging.
- **Key Takeaway**: Rovo strictly enforces Atlassian Access permissions, guaranteeing users only receive AI search results for content they are authorized to view.

---

## 27.8 Executive & Practitioner Knowledge Assessment

### Question 1: What foundational technology powers Atlassian Rovo's ability to synthesize context across Jira, Confluence, GitHub, and Google Drive?
- A) SQLite database files
- B) The Atlassian Teamwork Graph, which maps relationships between users, work items, documents, and connected third-party tools
- C) Web browser cookies
- D) Local text files

> **Answer Key & Socratic Rationale**:
> **Correct Answer: B** — The Atlassian Teamwork Graph models cross-tool relationships, enabling Rovo to synthesize enterprise context accurately.

### Question 2: How does Atlassian Rovo Search prevent unauthorized users from viewing confidential financial project data in search results?
- A) By encrypting all search results with a master key
- B) Rovo Search inherits and strictly enforces individual user Access Control Lists (ACLs) and Atlassian Access permissions at query time
- C) By hiding the search bar from non-managers
- D) Data is anonymized automatically

> **Answer Key & Socratic Rationale**:
> **Correct Answer: B** — Rovo respects user permission boundaries, ensuring AI search outputs only include data the requesting user is authorized to read.

### Question 3: In Atlassian Forge, which module definition in `manifest.yml` registers a new custom Rovo Agent?
- A) `modules: macro`
- B) `modules: rovo:agent`
- C) `modules: jira:issueProperty`
- D) `modules: webTrigger`

> **Answer Key & Socratic Rationale**:
> **Correct Answer: B** — The `rovo:agent` module key registers custom AI agents with specific prompts, names, and action bindings inside Forge.

### Question 4: What is the role of a Forge 'action' module when connected to a custom Rovo Agent in Jira Cloud?
- A) It formats text in bold
- B) It provides executable serverless JavaScript/Node.js code that allows the Rovo Agent to perform active operations in Jira (e.g., updating fields, transitioning issues)
- C) It deletes the Jira project
- D) It restarts the user's computer

> **Answer Key & Socratic Rationale**:
> **Correct Answer: B** — Action modules expose executable backend functions that Rovo Agents can invoke dynamically to perform side-effecting operations.

### Question 5: Why is developing custom Rovo Agent actions via Atlassian Forge safer than hosting external webhooks on a public server?
- A) Forge code executes within Atlassian's secure cloud boundary and enforces explicit manifest-declared OAuth 2.0 permission scopes
- B) Forge does not require passwords
- C) External webhooks are illegal in 2026
- D) Forge runs on paper

> **Answer Key & Socratic Rationale**:
> **Correct Answer: A** — Forge executes natively inside Atlassian infrastructure, eliminating external security perimeters and unmonitored API keys.

### Question 6: How does Rovo Chat assist a Product Owner during Sprint Backlog Refinement directly inside a Jira issue view?
- A) By writing C++ code automatically
- B) By summarizing issue discussions, identifying missing acceptance criteria, and pulling related Confluence spec pages directly into the chat sidebar
- C) By closing all open bugs automatically
- D) By changing the sprint start date

> **Answer Key & Socratic Rationale**:
> **Correct Answer: B** — Rovo Chat provides issue-in-context AI assistance, synthesizing issue comments, Confluence specs, and related tickets instantly.
"""

with open(os.path.join(PART8_DIR, "ch27_atlassian_rovo_jira_cloud.md"), "w", encoding="utf-8") as f:
    f.write(ch27_content)

print("Created Chapter 27 markdown.")
