import os

APP_A_PATH = 'appendices/appA_prompt_library.md'
APP_B_PATH = 'appendices/appB_jql_wiql_cheatsheet.md'
APP_C_PATH = 'appendices/appC_transformation_checklist.md'

os.makedirs('appendices', exist_ok=True)

# Generate Appendix A
appA_content = []
appA_content.append('# Appendix A: Enterprise AI Coaching Prompt Library\n')
appA_content.append('📌 EXECUTIVE COACHING GUARDRAIL: Over 100 Production-Tested Prompts for Agile Coaches, Scrum Masters, Product Owners & Enterprise Leaders\n')
appA_content.append('This comprehensive prompt engineering library contains 105 production-tested, role-specific system prompts engineered for Large Language Models (LLMs) and Model Context Protocol (MCP) agents operating in complex enterprise environments. Each prompt includes a System Persona, Context Boundary, Core Task Specification, Variable Template Parameters, and Standardized Output Schema.\n')

categories = [
    ("A.1 Strategic Leadership & Enterprise Agile Coaches (Prompts 01 - 21)", [
        ("Prompt 01: Executive OKR Alignment Diagnostic", "Enterprise Agile Coach & Strategic Advisor", "Executive leadership has drafted corporate OKRs, but they read like tactical feature delivery lists rather than empirical outcome metrics.", "Evaluate candidate OKRs, identify output biases, and rephrase Key Results into empirical customer or business outcomes.", "[INSERT DRAFT OKRS HERE]", ["1. Analysis of Current Output Bias", "2. Refactored Outcome-Based Key Results", "3. Quantitative Metrics & Data Source Mappings"]),
        ("Prompt 02: Portfolio Value Stream Prioritization (WSJF Scoring)", "Value Stream Management Expert", "The portfolio committee is overwhelmed with 40 competing initiatives, causing massive WIP and funding fragmentation.", "Calculate Weighted Shortest Job First (WSJF) scores for candidate epics and provide ranking rationale.", "[INSERT CANDIDATE EPICS WITH USER VALUE, TIME CRITICALITY, RROE, AND JOB SIZE]", ["1. WSJF Calculation Table", "2. Top 5 Priority Recommendation", "3. Deferred Epic Rationale"]),
        ("Prompt 03: Strategic Horizon Investment Slicing", "Portfolio Governance Architect", "Investment funding is unevenly allocated, starving Horizon 2 and Horizon 3 innovation.", "Analyze current project budget allocations across Horizon 1 (70%), Horizon 2 (20%), and Horizon 3 (10%) and rebalance.", "[INSERT CURRENT BUDGET ALLOCATIONS BY INITIATIVE]", ["1. Horizon Allocation Audit", "2. Budget Rebalancing Plan", "3. Risk & Growth Impact Assessment"]),
        ("Prompt 04: Enterprise Change Readiness & ADKAR Diagnostic", "Organizational Change Management Specialist", "A major enterprise DevOps and AI transition is facing passive resistance across mid-level management.", "Apply the ADKAR (Awareness, Desire, Knowledge, Ability, Reinforcement) model to assess change readiness and prescribe interventions.", "[INSERT STAKEHOLDER INTERVIEW FEEDBACK & SURVEY DATA]", ["1. ADKAR Maturity Scorecard", "2. Resistance Root Cause Analysis", "3. Tailored Change Management Action Plan"]),
        ("Prompt 05: Organizational Culture & Psychological Safety Audit", "Enterprise Culture Facilitator", "Engagement survey results indicate fear of failure, preventing teams from reporting production risks early.", "Diagnose systemic cultural friction points and design 4 blameless operational guardrails.", "[INSERT ANONYMIZED CULTURE SURVEY COMMENTS]", ["1. Cultural Health Index", "2. Systemic Friction Drivers", "3. 4 Blameless Process Protocols"]),
        ("Prompt 06: Executive Steering Committee Quarterly Briefing Synthesizer", "Executive Communications Lead", "Quarterly transformation metrics need to be presented to the C-suite and Board of Directors.", "Synthesize raw telemetry data into a 1-page executive summary focusing on Flow Velocity, Time to Market, and ROI.", "[INSERT RAW TELEMETRY & PROJECT STATUS REPORTS]", ["1. Executive Summary Bullet Points", "2. Flow & Business Outcome Trends", "3. Strategic Risk Escalations & Decisions Required"]),
        ("Prompt 07: Scaling Framework Selection & Tailoring Guide", "Enterprise Transformation Architect", "The organization is struggling with heavy SAFe overhead and considering descaling to LeSS or Spotify topologies.", "Compare SAFe, LeSS, and Stream-Aligned Squad topologies against organizational context and recommend optimal framework tailoring.", "[INSERT ORG STRUCTURE, PRODUCT PORTFOLIO & TEAM COUNT]", ["1. Framework Trade-off Comparison Table", "2. Recommended Tailored Operating Model", "3. Governance Streamlining Steps"]),
        ("Prompt 08: Enterprise Flow Bottleneck Interception & Economic Loss Evaluator", "Flow Systems Engineer", "Lead times for strategic features have inflated from 30 days to 90 days across 5 value streams.", "Analyze Cumulative Flow Data (CFD) and queue wait times to calculate Cost of Delay and pinpoint flow bottlenecks.", "[INSERT CFD STAGE DURATIONS & COST OF DELAY ESTIMATES]", ["1. Flow Bottleneck Location & Cause", "2. Cost of Delay Financial Impact", "3. Immediate WIP Limit & Queue Reduction Actions"]),
        ("Prompt 09: Enterprise AI Governance & Ethics Policy Generator", "AI Risk & Compliance Officer", "Development squads are leveraging unvetted LLMs, raising data privacy, IP leakage, and compliance concerns.", "Draft an Enterprise Responsible AI Policy covering model selection, data anonymization, and human-in-the-loop validation.", "[INSERT CURRENT AI USAGE CASES & REGULATORY REQ]", ["1. Policy Mandate & Scope", "2. Data Privacy & IP Protection Guardrails", "3. Compliance Verification & Audit Checklist"]),
        ("Prompt 10: Vendor / Partner Agile Contract Alignment Audit", "Agile Procurement & Legal Advisor", "Third-party offshore vendors operate under fixed-scope, fixed-price contracts that conflict with internal agile iterations.", "Redraft vendor SOW (Statement of Work) terms to align with agile deliverables, joint risk sharing, and capacity-based pricing.", "[INSERT CURRENT VENDOR SOW CLAUSES]", ["1. Contractual Friction Analysis", "2. Proposed Agile SOW Clause Modifications", "3. Performance SLA & Quality Metrics"]),
        ("Prompt 11: Multi-Value Stream Dependency Resolution Protocol", "Enterprise Dependency Facilitator", "Cross-team dependencies between Digital Channels and Core Banking are delaying quarterly releases.", "Create a Dependency Mapping Matrix and establish an automated cross-team coordination protocol.", "[INSERT LIST OF DEPENDENT EPICS & TARGET DATES]", ["1. Dependency Matrix Visualization Table", "2. Critical Path Identification", "3. Synchronization Protocol & Governance Cadence"]),
        ("Prompt 12: Lean-Agile Guardrail Financial Budgeting Generator", "Lean Financial Controller", "Traditional annual budgeting processes create rigid project silos and prevent dynamic re-funding of high-value features.", "Design a Lean-Agile Participatory Budgeting framework with dynamic funding guardrails per Value Stream.", "[INSERT ANNUAL PORTFOLIO BUDGET & VALUE STREAM LIST]", ["1. Dynamic Funding Allocation Schema", "2. Guardrail Threshold Criteria", "3. Governance Approval Workflow"]),
        ("Prompt 13: Talent Capability Matrix & Agile Reskilling Roadmap", "Agile Capability Development Director", "Engineering leads lack cloud-native and AI prompt engineering skills, stalling technical transformation.", "Build an Enterprise Capability Skill Matrix and construct a 6-month role-based learning path.", "[INSERT CURRENT TEAM SKILL ASSESSMENTS & TARGET ROLES]", ["1. Skill Gap Analysis Table", "2. 6-Month Reskilling Curriculum", "3. Competency Evaluation Criteria"]),
        ("Prompt 14: Enterprise Regulatory Compliance & Audit Matrix", "Governance & Audit Assurance Lead", "Auditors demand evidence of regulatory compliance (SOX/GDPR/HIPAA) without slowing down automated CI/CD pipelines.", "Map regulatory compliance controls directly into automated pipeline security gates and issue tracking audit logs.", "[INSERT REGULATORY COMPLIANCE REQUIREMENTS]", ["1. Automated Audit Gate Matrix", "2. Pipeline Verification Proof Schema", "3. Auditor Reporting Template"]),
        ("Prompt 15: Agile Center of Excellence (CoE) Charter & Roadmap", "Agile Transformation CoE Director", "The Agile CoE lacks a clear strategic charter, leading to inconsistent coaching standards across business units.", "Author an Enterprise Agile CoE Charter, defining mission, service offerings, KPIs, and multi-year transformation roadmap.", "[INSERT CURRENT TRANSFORMATION GOALS & COACHING HEADCOUNT]", ["1. CoE Mission & Vision Statement", "2. Service Catalog & Coaching Offerings", "3. 3-Year Transformation Milestone Roadmap"]),
        ("Prompt 16: Dynamic Team Topology Optimizer & Stream-Aligned Squad Mapper", "Organizational Design Architect", "Component-based team silos are causing excessive handoffs and communication overhead.", "Reorganize engineering teams into Team Topologies (Stream-Aligned, Complicated-Subsystem, Enabling, Platform).", "[INSERT SYSTEM ARCHITECTURE & CURRENT TEAM LIST]", ["1. Team Topology Blueprint", "2. Interaction Modes (Collaboration, X-as-a-Service, Facilitating)", "3. Transition Steps"]),
        ("Prompt 17: C-Suite Executive Coaching Conversation Simulator", "Executive Leadership Coach", "A VP of Engineering insists on micro-managing squad velocity and using story points as performance metrics.", "Simulate a 1-on-1 executive coaching dialogue using powerful Socratic questioning to shift perspective to empirical outcomes.", "[INSERT VP SCENARIO & CURRENT FRICTION POINTS]", ["1. Diagnostic Perspective Analysis", "2. Step-by-Step Socratic Coaching Script", "3. Follow-up Commitments & Metrics"]),
        ("Prompt 18: Post-Merger Operational & Culture Integration Strategy", "M&A Operational Integration Lead", "Two merged tech organizations operate with conflicting issue tracking tools, agile frameworks, and release cycles.", "Design a 90-day operational harmonization strategy to unify tools, processes, and engineering cultures.", "[INSERT COMPANY A AND COMPANY B PROCESS SPECS]", ["1. Process & Tool Gap Analysis", "2. 90-Day Harmonization Plan", "3. Risk Mitigation & Cultural Integration Guardrails"]),
        ("Prompt 19: Enterprise Continuous Improvement Kata Generator", "Lean-Agile Operational Excellence Lead", "Teams plateau after initial agile adoption and stop pursuing continuous improvement experiments.", "Generate an Improvement Kata structure defining Target Condition, Current Condition, Obstacles, and Next Experiment.", "[INSERT TEAM CURRENT METRICS & TARGET GOALS]", ["1. Target Condition Definition", "2. Obstacle Inventory", "3. Rapid PDCA Experiment Design"]),
        ("Prompt 20: Enterprise VSM Flow Velocity vs Business Outcome Correlator", "Value Stream Telemetry Lead", "Leadership questions whether improvements in Flow Velocity are driving real business growth.", "Correlate Flow Metrics (Flow Velocity, Flow Time, Flow Load) with business KPIs (Revenue Growth, NPS, Churn).", "[INSERT 4-QUARTER FLOW METRICS & BUSINESS DATA]", ["1. Correlation Analysis Summary", "2. High-Impact Value Levers", "3. Strategic Recommendation for Next Quarter"]),
        ("Prompt 21: Enterprise Portfolio Budget Rebalancing Engine", "Portfolio Financial Architect", "Mid-year market shifts require immediate re-allocation of 20% portfolio funding from low-performing products.", "Assess product performance data and re-allocate budget to high-performing growth products.", "[INSERT PRODUCT PERFORMANCE METRICS & BUDGETS]", ["1. Re-allocation Matrix", "2. Investment Pivot Rationale", "3. Execution Timeline"])
    ]),
    ("A.2 Scrum Masters & Agile Facilitators (Prompts 22 - 42)", [
        ("Prompt 22: Sprint Planning Capacity & Buffer Modeling Engine", "Senior Scrum Master", "Teams consistently over-commit during Sprint Planning, leading to high spillover and team burnout.", "Calculate historical velocity standard deviation, factor in planned leave, and establish an optimal commitment buffer.", "[INSERT HISTORICAL VELOCITY & SPRINT TEAM AVAILABILITY]", ["1. Net Recommended Sprint Capacity", "2. Calculated Commitment Buffer", "3. Risk-Adjusted Sprint Backlog Selection"]),
        ("Prompt 23: Daily Standup Impediment Signal Extractor", "Agile Facilitator", "Daily Standups run for 30 minutes, devolving into status reporting rather than impediment identification.", "Extract hidden impediments and blockages from developer status statements and route to resolution owner.", "[INSERT DAILY STANDUP TRANSCRIPT OR NOTES]", ["1. Impediment Signal Summary Table", "2. Root Cause Classification", "3. Assigned Action Items & SLAs"]),
        ("Prompt 24: Retrospective Psychological Safety & Action Clustering", "Empathetic Team Facilitation Coach", "Retrospective feedback is timid and fails to address deep technical debt or interpersonal tensions.", "Cluster anonymous retro feedback, score emotional sentiment, and formulate 3 actionable, blameless Kaizen items.", "[INSERT ANONYMIZED RETRO FEEDBACK NOTES]", ["1. Categorized Theme Matrix", "2. Sentiment Intensity Analysis", "3. 3 High-Impact Action Items"]),
        ("Prompt 25: Team Psychological Safety Index Diagnostic Evaluator", "Agile Team Coach", "Team members hesitate to ask for help or admit mistakes during sprint execution.", "Evaluate survey responses against Amy Edmondson's Psychological Safety framework and generate 4 facilitation interventions.", "[INSERT PSYCHOLOGICAL SAFETY SURVEY DATA]", ["1. Psychological Safety Index Score", "2. Weakness Area Identification", "3. 4 Team Facilitation Exercises"]),
        ("Prompt 26: Empirical Sprint Goal Realism & Commitment Validator", "Scrum Master", "Sprint Goals are often generic statements like 'Complete all user stories', leading to lack of focus.", "Draft a singular, value-driven Sprint Goal based on backlog items and validate its empirical realism.", "[INSERT CANDIDATE SPRINT BACKLOG ITEMS]", ["1. Refactored Singular Sprint Goal", "2. Value Alignment Rationale", "3. Goal Completion Indicators"]),
        ("Prompt 27: Definition of Done (DoD) & Definition of Ready (DoR) Generator", "Agile Quality Coach", "Stories enter sprints with vague acceptance criteria, causing frequent re-work and QA bottlenecks.", "Formulate a robust Definition of Ready (DoR) and Definition of Done (DoD) tailored for cloud microservices teams.", "[INSERT TEAM TECH STACK & CURRENT RE-WORK ISSUES]", ["1. Definition of Ready Checklist", "2. Definition of Done Quality Gates", "3. Squad Adoption Protocol"]),
        ("Prompt 28: Sprint Velocity Variance & Volatility Root Cause Analyzer", "Scrum Master & Data Analyst", "Velocity fluctuates wildly (+/- 50%) sprint over sprint, preventing predictable release forecasting.", "Analyze velocity historical data, identify spike and drop causes, and prescribe stabilization techniques.", "[INSERT 10-SPRINT VELOCITY & SPILLOVER DATA]", ["1. Velocity Variance Scorecard", "2. Primary Volatility Drivers", "3. Stabilization Action Plan"]),
        ("Prompt 29: Working Agreement & Team Charter Synthesizer", "Agile Team Facilitator", "A newly formed hybrid squad experiences confusion over core hours, code review SLAs, and communication channels.", "Synthesize team discussion inputs into a clean, binding Team Working Agreement.", "[INSERT TEAM DISCUSSION INPUTS & PREFERENCES]", ["1. Communication & Core Hours Agreement", "2. Code Review & PR SLA Rules", "3. Meeting Norms & Escalation Path"]),
        ("Prompt 30: Team Conflict Resolution & Socratic Mediation Script", "Agile Conflict Mediator", "A senior architect and lead developer have reached a deadlock over microservice vs monolith architecture.", "Provide a structured Socratic dialogue script to mediate technical disagreement and reach objective compromise.", "[INSERT ARCHITECTURAL DEADLOCK DETAILS]", ["1. Core Conflict Analysis", "2. Step-by-Step Socratic Mediation Script", "3. Objective Evaluation Criteria"]),
        ("Prompt 31: WIP Limit Violation Diagnostic & Swarming Facilitator", "Kanban Coach", "The team's In-Progress column has 18 active stories for 6 developers, causing high context switching.", "Identify WIP limit violations, analyze task blockage, and formulate a squad swarming execution plan.", "[INSERT KANBAN BOARD STATE DATA]", ["1. WIP Violation Diagnostic Summary", "2. Swarming Target Identification", "3. Immediate Work Item Redistribution Plan"]),
        ("Prompt 32: Sprint Review & Stakeholder Demo Storytelling Script", "Agile Showcase Facilitator", "Sprint demos are dry technical recites of code changes that fail to engage business stakeholders.", "Transform technical sprint deliverables into a compelling customer-centric demo story script.", "[INSERT COMPLETED SPRINT USER STORIES]", ["1. Customer Persona Narrative Context", "2. Step-by-Step Demo Flow Script", "3. Key Feedback Capture Prompts"]),
        ("Prompt 33: Backlog Refinement Pacing & Story Point Calibration Guide", "Scrum Master", "Refinement sessions drag on without consensus on story points, leading to estimation fatigue.", "Establish a Planning Poker calibration guide with explicit benchmark reference stories for 1, 2, 3, 5, 8 points.", "[INSERT HISTORICAL COMPLETED STORIES WITH ESTIMATES]", ["1. Story Point Reference Calibration Grid", "2. Refinement Timeboxing Strategy", "3. Estimation Disagreement Resolution Rule"]),
        ("Prompt 34: Escalated Impediment SLA & Bottleneck Tracker", "Agile Operations Lead", "Impediments raised during daily standups sit unresolved in management queues for weeks.", "Draft an Impediment Escalation SLA Matrix with automated trigger conditions and owner accountability.", "[INSERT UNRESOLVED IMPEDIMENT LIST & TIMELINES]", ["1. Escalation Matrix Grid", "2. SLA Severity Levels", "3. Automated Escalation Protocol"]),
        ("Prompt 35: Pair / Mob Programming Facilitation & Knowledge Sharing Script", "Technical Agile Facilitator", "Knowledge silos exist around core legacy modules, making 1 developer a single point of failure.", "Design a structured Mob / Pair Programming session framework to transfer critical domain knowledge.", "[INSERT TARGET LEGACY MODULE & TEAM MEMBERS]", ["1. Session Roles (Driver, Navigator, Mob)", "2. Rotation Cadence & Rules", "3. Learning Verification Checklist"]),
        ("Prompt 36: Continuous Feedback & Gratitude Board Facilitator", "Agile Culture Facilitator", "Team morale is low due to high pressure and lack of peer recognition.", "Facilitate a structured Kudo / Gratitude exercise integrated into end-of-sprint ceremonies.", "[INSERT TEAM CONTEXT & RECENT ACCOMPLISHMENTS]", ["1. Facilitation Guide & Prompts", "2. Recognition Template", "3. Long-term Morale Integration Plan"]),
        ("Prompt 37: Burndown & Burnup Drift Root Cause Diagnostic", "Scrum Master", "The sprint burndown chart remains flat until day 9, followed by a sudden artificial cliff drop on day 10.", "Diagnose the root cause of late-sprint batching and design intra-sprint flow tracking indicators.", "[INSERT SPRINT BURNDOWN DAILY DATA]", ["1. Burndown Pattern Analysis", "2. Root Cause (Batch QA, Late PRs, Large Stories)", "3. Mid-Sprint Flow Checklist"]),
        ("Prompt 38: Cross-Skill Matrix & Single-Point-of-Failure (SPOF) Detector", "Squad Coach", "Sprint commitments fail whenever the sole QA automation engineer is absent.", "Construct a Squad Cross-Skill Heatmap and design a peer-shadowing plan to eliminate SPOFs.", "[INSERT TEAM MEMBER SKILLS & ROLES]", ["1. Cross-Skill Heatmap Matrix", "2. SPOF Vulnerability Points", "3. Cross-Training Action Plan"]),
        ("Prompt 39: Agile Maturity Health Radar Assessment", "Agile Assessor", "Leadership wants a qualitative and quantitative assessment of squad agile maturity across 6 dimensions.", "Generate an Agile Health Radar Assessment survey across Flow, Quality, Collaboration, Value, Automation, Culture.", "[INSERT SQUAD PERFORMANCE DATA]", ["1. Health Radar Metric Scoring Grid", "2. Strength & Gap Analysis", "3. Targeted Coaching Interventions"]),
        ("Prompt 40: Hybrid / Remote Team Engagement & Ceremony Script", "Remote Agile Facilitator", "Distributed team members in Europe and Asia feel disconnected and silent during virtual events.", "Design an asynchronous-first hybrid ceremony model with interactive Miro/Mural engagement triggers.", "[INSERT TEAM TIMEZONES & CURRENT CEREMONY SCHEDULE]", ["1. Asynchronous vs Synchronous Event Breakdown", "2. Virtual Interaction Prompts", "3. Facilitation Playbook"]),
        ("Prompt 41: Kaizen Continuous Improvement Experiment Canvas", "Agile Excellence Coach", "Improvements identified in retrospectives are forgotten by the next sprint.", "Convert retrospective action items into testable Kaizen hypotheses with measurable pass/fail criteria.", "[INSERT RETRO ACTION ITEMS]", ["1. Kaizen Experiment Canvas", "2. Success Criteria & Metrics", "3. Sprint Review Audit Date"]),
        ("Prompt 42: Daily Standup Micro-Bot Automation Prompts", "Agile Automation Specialist", "Teams want to automate preliminary daily standup collection via Slack/Teams bot.", "Generate bot prompt strings for daily check-in querying progress, goal focus, and blockers.", "[INSERT TEAM CHANNEL & CHAT BOT TOOL]", ["1. Automated Chat Bot Prompts", "2. Escalation Keyword Parser Rules", "3. Summary Dashboard Format"])
    ]),
    ("A.3 Product Owners & Product Managers (Prompts 43 - 63)", [
        ("Prompt 43: INVEST User Story Slicing & SPIDR Decomposition", "Senior Product Owner", "A 13-story-point feature request is too complex for a single sprint and risks total spillover.", "Decompose the large epic into 4 smaller, independent user stories using SPIDR (Spike, Path, Interface, Data, Rules).", "[INSERT LARGE EPIC DESCRIPTION & ACCEPTANCE REQS]", ["1. SPIDR Slicing Analysis", "2. 4 Sliced User Story Cards", "3. INVEST Compliance Rating"]),
        ("Prompt 44: Automated Gherkin BDD Acceptance Criteria Synthesizer", "Product Analyst & QA Specialist", "Developers misinterpret user story requirements, leading to high bug rates in integration testing.", "Convert raw user story descriptions into 3 standardized Gherkin BDD scenarios (Happy Path, Boundary, Error).", "[INSERT RAW USER STORY STATEMENT]", ["1. Given-When-Then Happy Path Scenario", "2. Boundary Condition Scenario", "3. Error Handling Exception Scenario"]),
        ("Prompt 45: Customer Persona & Empathy Map Synthesizer", "Product Discovery Lead", "Product features lack focus because the squad lacks a unified understanding of target user personas.", "Synthesize user research notes into a detailed Persona Profile and Empathy Map (Says, Thinks, Does, Feels).", "[INSERT RAW USER INTERVIEWS & SURVEY DATA]", ["1. Persona Profile Blueprint", "2. 4-Quadrant Empathy Map", "3. Primary Pain Points & Opportunities"]),
        ("Prompt 46: Kano Model Feature Categorization & Priority Matrix", "Product Strategist", "Stakeholders demand 50 new features, making prioritization subject to political HIPPO influence.", "Classify features into Kano categories (Basic, Performance, Delighter) to drive empirical backlog ranking.", "[INSERT LIST OF CANDIDATE FEATURES & USER FEEDBACK]", ["1. Kano Categorization Grid", "2. Feature Priority Ranking", "3. Strategic Product Roadmap Recommendation"]),
        ("Prompt 47: Customer Journey Mapping & Friction Point Identifier", "UX & Product Discovery Coach", "Users drop off during the multi-step account onboarding workflow, causing low conversion rates.", "Map the end-to-end customer journey, identify emotional pain points, and propose 3 frictionless design changes.", "[INSERT ONBOARDING STEPS & ANALYTICS DROP-OFF DATA]", ["1. Customer Journey Flow Matrix", "2. Friction Point Identification", "3. UX & Backlog Feature Interventions"]),
        ("Prompt 48: Feature Hypothesis & MVP Experiment Design Canvas", "Lean Startup & Product Manager", "Large sums are spent building full-scale features before validating whether customers actually want them.", "Formulate a testable Feature Hypothesis and design a minimum viable experiment (Concierge, Wizard of Oz, Landing Page).", "[INSERT PROPOSED FEATURE IDEA]", ["1. Feature Hypothesis Statement", "2. MVP Experiment Design", "3. Validation Metric & Pass Threshold"]),
        ("Prompt 49: Feature Cross-Team Dependency & Precedence Matrix", "Product Operations Manager", "Product release dates are missed because component team dependencies were discovered mid-sprint.", "Analyze feature technical requirements to build a Feature Precedence & Dependency Tree.", "[INSERT FEATURE TECH REQS & DEPENDENT SQUADS]", ["1. Dependency Precedence Tree", "2. Risk Critical Path", "3. Alignment Schedule for POs"]),
        ("Prompt 50: Product Vision & Elevator Pitch Generator", "Lead Product Manager", "The engineering squad does not understand how their daily tasks connect to the long-term product vision.", "Craft a compelling Geoff Moore Product Vision Statement and 60-second Elevator Pitch.", "[INSERT PRODUCT TARGET AUDIENCE, PROBLEM & UNIQUE SELLING PROP]", ["1. Geoff Moore Product Vision Template", "2. 60-Second Elevator Pitch Script", "3. Squad Alignment Narrative"]),
        ("Prompt 51: Multi-Horizon Release Roadmap & Milestone Planner", "Product Portfolio Manager", "Roadmaps are treated as rigid delivery schedules, creating friction when market conditions shift.", "Design an outcome-based Multi-Horizon Release Roadmap (Now, Next, Later) aligned with strategic milestones.", "[INSERT FEATURE BACKLOG & STRATEGIC MILESTONES]", ["1. Now / Next / Later Roadmap Matrix", "2. Outcome Goals per Horizon", "3. Stakeholder Communication Script"]),
        ("Prompt 52: Backlog Prioritization (MoSCoW & RICE Scoring Engine)", "Product Backlog Manager", "Backlog items are unranked, causing developers to pull low-value items into active sprints.", "Calculate RICE (Reach, Impact, Confidence, Effort) scores for candidate items and apply MoSCoW buckets.", "[INSERT BACKLOG ITEMS WITH ESTIMATED RICE PARAMETERS]", ["1. RICE Score Table", "2. MoSCoW Bucket Classification", "3. Recommended Sprint Backlog Priority"]),
        ("Prompt 53: Product Analytics & User Event Telemetry Tracking Plan", "Product Analytics Lead", "The product team has no visibility into how customers interact with newly released features.", "Design a Product Telemetry Event Tracking Plan specifying user actions, properties, and analytics triggers.", "[INSERT NEW FEATURE FLOW & USER STEPS]", ["1. Event Tracking Data Schema", "2. User Action Trigger Matrix", "3. Success Analytics Dashboard Mockup"]),
        ("Prompt 54: Customer Interview Script & Insight Extraction Engine", "User Research Coach", "User interview sessions produce unstructured feedback that is difficult to translate into user stories.", "Generate an unbiased User Interview Script and an Insight Extraction Template.", "[INSERT RESEARCH OBJECTIVE & TARGET USER TYPE]", ["1. Structured Interview Script", "2. Insight Extraction Template", "3. User Story Synthesis Schema"]),
        ("Prompt 55: Competitive Feature Matrix & Market Differentiation Audit", "Product Marketing & Strategy Director", "Competitors are releasing AI-driven features, threatening market share in core product lines.", "Perform a competitive feature audit across 4 primary rivals and identify blue-ocean differentiation opportunities.", "[INSERT COMPETITOR FEATURE LISTS & MARKET REVIEWS]", ["1. Competitive Feature Matrix Table", "2. Differentiation Gap Analysis", "3. Strategic Feature Recommendations"]),
        ("Prompt 56: Technical Debt vs Customer Value Trade-off Modeler", "Product Owner & Tech Lead Liaison", "Tech leads demand 4 Sprints of pure refactoring, while business leaders demand 100% new features.", "Build a balanced trade-off allocation model dividing sprint capacity between Features, Debt, Bugs, and Architecture.", "[INSERT TECH DEBT BACKLOG & BUSINESS FEATURE REQUESTS]", ["1. Capacity Allocation Ratio (e.g., 60/20/10/10)", "2. Trade-off ROI Rationale", "3. Joint PO/Tech Lead Agreement"]),
        ("Prompt 57: User Story Mapping Canvas & Spine Builder", "Product Discovery Facilitator", "Squads build features in isolated vertical slices that don't create a functional user end-to-end flow.", "Construct a User Story Map featuring User Activities, Steps, and Sliced Release Tranches (MVP, v1.1, v2.0).", "[INSERT END-TO-END USER GOAL & BACKLOG CARDS]", ["1. Story Map Backbone & Activity Grid", "2. Sliced Release Tranche Matrix", "3. MVP Scope Boundary Line"]),
        ("Prompt 58: Customer Feedback Sentiment Classifier & Feature Request Clustering", "Product Operations Analyst", "Thousands of Zendesk and app store reviews are unorganized, hiding critical feature requests.", "Classify feedback comments by sentiment and cluster into top 5 requested feature enhancements.", "[INSERT RAW FEEDBACK COMMENTS & REVIEWS]", ["1. Sentiment Breakdown Chart Data", "2. Top 5 Feature Cluster Analysis", "3. High-Priority Bug Escalations"]),
        ("Prompt 59: Non-Functional Requirement (NFR) Specification Generator", "Product Architect & PO", "Features pass functional QA but crash in production under high load due to missing performance specs.", "Formulate explicit, testable NFR specs for Latency, Availability, Scalability, Security, and Accessibility.", "[INSERT FEATURE FUNCTIONAL SPECS & USER LOAD EXPECTATIONS]", ["1. NFR Specification Matrix", "2. Acceptance Criteria SLAs", "3. Automated Testing Verification Plan"]),
        ("Prompt 60: Product Monetization & Value Proposition Packaging Modeler", "Product Growth Lead", "Pricing tiers are outdated and fail to capture value from enterprise power users.", "Design a value-metric based SaaS pricing grid aligned with feature tiers and usage limits.", "[INSERT CURRENT PRICING & USER USAGE METRICS]", ["1. Tiered Pricing Model Matrix", "2. Value Metric Rationale", "3. Upsell Trigger Points"]),
        ("Prompt 61: User Churn Mitigation & Re-engagement Feature Brainstormer", "Product Retention Specialist", "30-day user retention has dropped by 15% following a recent major app overhaul.", "Analyze churn drop-off points and brainstorm 4 targeted re-engagement feature hooks.", "[INSERT USER CHURN DATA & FUNNEL DROPOFF]", ["1. Churn Root Cause Analysis", "2. 4 Retention Feature Hooks", "3. A/B Testing Validation Strategy"]),
        ("Prompt 62: Early Adopter Beta Feedback & Bug Severity Matrix", "Product Launch Manager", "Beta launch results in hundreds of bug reports without clear severity classification.", "Categorize beta feedback into Critical Blocker, Major Defect, Minor Polish, and Feature Request.", "[INSERT RAW BETA FEEDBACK & BUG REPORTS]", ["1. Bug Severity Matrix", "2. Release Gate Decision (Go / No-Go)", "3. Post-Beta Patch Plan"]),
        ("Prompt 63: Product Manager AI Prompt Suite for Backlog Grooming", "Productivity Coach", "Product Owners spend 15 hours a week writing user stories manually.", "Create an automated prompt workflow that transforms meeting transcripts into polished user stories.", "[INSERT MEETING TRANSCRIPT EXCERPT]", ["1. Story Title & Description", "2. Acceptance Criteria", "3. User Story Map Placement"])
    ]),
    ("A.4 Technical Leads, Architects & Flow Engineers (Prompts 64 - 84)", [
        ("Prompt 64: Architecture Decision Record (ADR) Generator", "Principal Software Architect", "Engineers keep questioning past architectural choices because design rationale was never documented.", "Draft a formal Architecture Decision Record (ADR) detailing Context, Decision, Status, and Consequences.", "[INSERT ARCHITECTURAL CHOICE & TECH STACK CONTEXT]", ["1. ADR Header & Status", "2. Context & Problem Statement", "3. Decision Rationale & Positive/Negative Consequences"]),
        ("Prompt 65: Technical Debt Indexing & Refactoring ROI Calculator", "Lead Systems Engineer", "Management refuses to allocate time for technical debt cleanup because financial ROI is unclear.", "Quantify technical debt using Code Complexity, Defect Density, and Developer Friction to calculate ROI.", "[INSERT CODE METRICS, DEFECT HISTORY & DEBT DESCRIPTION]", ["1. Tech Debt Index Score", "2. Cost of Inaction (Financial Loss)", "3. Refactoring Proposal & Expected ROI"]),
        ("Prompt 66: API Contract & OpenAPI Specification Validator", "Integration Architect", "Frontend and backend squads break each other's builds due to uncoordinated API payload schema changes.", "Generate a standardized OpenAPI 3.0 YAML spec and establish a strict contract-first validation process.", "[INSERT API ENDPOINT REQUIREMENTS & DATA FIELDS]", ["1. Validated OpenAPI 3.0 YAML Spec", "2. Breaking Change Audit Checklist", "3. Mock Server Test Integration Plan"]),
        ("Prompt 67: Microservices Boundary & DDD Bounded Context Mapper", "Domain-Driven Design Specialist", "A monolithic database causes tight coupling across microservices, creating distributed deployment deadlocks.", "Apply DDD Strategic Design to define Bounded Contexts, Domain Events, and Aggregate Boundaries.", "[INSERT DOMAIN ENTITIES & DATA FLOW DESCRIPTION]", ["1. Bounded Context Map", "2. Domain Event Flow Schema", "3. Database Decoupling Roadmap"]),
        ("Prompt 68: CI/CD Pipeline Cycle Time & Bottleneck Audit", "DevOps Lead Engineer", "CI/CD pipeline builds take 45 minutes, creating a major bottleneck in squad release flow.", "Analyze pipeline stage durations (Compile, Unit Test, Security Scan, Deploy) and prescribe 4 optimization steps.", "[INSERT PIPELINE STAGE TIMINGS & LOGS]", ["1. Pipeline Bottleneck Breakdown", "2. Parallelization & Caching Strategy", "3. Target Pipeline Execution Time"]),
        ("Prompt 69: Zero-Trust Security & Automated Scanner Integration", "DevSecOps Lead Architect", "Security reviews occur at the end of releases, discovering critical vulnerabilities that delay launches.", "Design an automated DevSecOps pipeline gate incorporating SAST, DAST, SCA, and Container scanning.", "[INSERT CI/CD TOOLING & COMPLIANCE REQUIREMENTS]", ["1. DevSecOps Pipeline Architecture", "2. Automated Scan Gate Rules", "3. Vulnerability Remediation SLA Grid"]),
        ("Prompt 70: Automated Static Code Analysis & Peer Review Checklist", "Staff Software Engineer", "Code reviews are inconsistent, focus on minor syntax formatting, and miss critical concurrency bugs.", "Generate an automated Static Code Analysis rule-set and a focused Peer Code Review Checklist.", "[INSERT PROGRAMMING LANGUAGE & FRAMEWORK SPECS]", ["1. Static Analysis Rule Configuration", "2. 5-Point Peer Review Checklist", "3. Automated PR Bot Integration Guide"]),
        ("Prompt 71: Blameless Incident Post-Mortem & 5-Whys Root Cause Analyzer", "Site Reliability Engineer (SRE)", "A 2-hour production outage caused severe customer disruption and led to finger-pointing between teams.", "Conduct a blameless 5-Whys root cause analysis and generate 4 systemic preventive action items.", "[INSERT INCIDENT TIMELINE & SYSTEM LOGS]", ["1. Incident Summary & Timeline", "2. 5-Whys Root Cause Chain", "3. Systemic Prevention Action Plan"]),
        ("Prompt 72: OpenTelemetry Observability & Tracing Architecture Plan", "Observability Engineer", "Engineers struggle to diagnose production bugs in microservices due to lack of distributed tracing.", "Design an OpenTelemetry instrumentation framework defining Metrics, Logs, and Traces (MELT).", "[INSERT MICROSERVICES TOPOLOGY & TECH STACK]", ["1. MELT Telemetry Architecture", "2. Correlation ID Propagation Strategy", "3. Alert Threshold Definitions"]),
        ("Prompt 73: Cloud Infrastructure Cost Optimization & FinOps Auditor", "Cloud FinOps Architect", "AWS cloud spend has exceeded quarterly budgets by 35% without a corresponding increase in user traffic.", "Analyze cloud infrastructure usage and generate a FinOps cost reduction blueprint.", "[INSERT CLOUD BILLING BREAKDOWN & INSTANCE USAGE]", ["1. Waste Identification Summary", "2. Rightsizing & Reserved Instance Plan", "3. Estimated Monthly Savings"]),
        ("Prompt 74: Chaos Engineering Resilience Scenario Generator", "Resilience Engineer", "The system has single-point-of-failure risks during cloud region failover events.", "Design 3 Chaos Engineering experiments (Latency Injection, Node Failure, Network Partition) using Chaos Mesh/Gremlin.", "[INSERT SYSTEM INFRASTRUCTURE DIAGRAM & CRITICAL PATH]", ["1. Chaos Experiment Hypothesis", "2. Steady-State Metric Definition", "3. Injection Execution Script"]),
        ("Prompt 75: Database Schema Migration & Zero-Downtime Blueprint", "Lead Database Architect", "Database migrations require 4 hours of downtime, violating 99.99% availability SLAs.", "Design an Expand-Contract (Blue/Green Schema) migration pattern for zero-downtime database updates.", "[INSERT TARGET SCHEMA CHANGES & CURRENT DB SIZE]", ["1. Expand-Contract Execution Steps", "2. Backward-Compatible View Strategy", "3. Rollback Safety Protocol"]),
        ("Prompt 76: Developer Experience (DevEx) & Inner-Loop Friction Audit", "DevEx Engineering Manager", "Local environment setup takes new developers 5 days, slowing onboarding and inner-loop productivity.", "Audit developer inner-loop friction and specify containerized dev environments (DevContainers/Gitpod).", "[INSERT CURRENT LOCAL SETUP STEPS & TOOLING]", ["1. DevEx Friction Scorecard", "2. DevContainer Configuration Spec", "3. Target Onboarding Duration"]),
        ("Prompt 77: Model Context Protocol (MCP) Tool & Server Spec Blueprint", "AI Systems Integrator", "Squads want to expose internal Jira and GitHub APIs to AI agents via Model Context Protocol (MCP).", "Write a complete MCP Server JSON Schema definition for custom tools and resource endpoints.", "[INSERT API SPECS TO EXPOSE TO AI AGENTS]", ["1. MCP Server Manifest JSON", "2. Tool Prompt Definitions", "3. Security Authentication Protocol"]),
        ("Prompt 78: Infrastructure-as-Code (Terraform/K8s) Guardrail Audit", "Infrastructure Security Lead", "Misconfigured Kubernetes manifests and Terraform scripts frequently expose public S3 buckets.", "Formulate static analysis security rules (Checkov/tfsec) to enforce IaC compliance guardrails.", "[INSERT TERRAFORM / KUBERNETES MANIFEST SNIPPETS]", ["1. IaC Security Violation Analysis", "2. Automated Scan Policy Rules", "3. Remediated Code Manifests"]),
        ("Prompt 79: Automated Regression Test Slicing & Flaky Test Detector", "QA Automation Lead", "Regression test suite takes 6 hours to run and exhibits a 15% flaky test failure rate.", "Establish a test-impact analysis slicing strategy and flaky test quarantine protocol.", "[INSERT TEST SUITE EXECUTION METRICS & FLAKY LOGS]", ["1. Test Suite Slicing Taxonomy", "2. Flaky Test Detection Algorithm", "3. Fast-Feedback Test Gate Schema"]),
        ("Prompt 80: Data Pipeline & Real-Time ETL Quality Validator", "Data Engineering Lead", "Data warehouse reports display corrupted metrics due to unvalidated upstream API schema changes.", "Design a Great Expectations data quality validation pipeline for incoming ETL data streams.", "[INSERT ETL DATA SCHEMA & PIPELINE STAGES]", ["1. Data Quality Expectation Rules", "2. Automated Alerting Rules", "3. Data Lineage Recovery Schema"]),
        ("Prompt 81: Open-Source Dependency Security & License Compliance Scanner", "Software Supply Chain Security Lead", "Developers unknowingly import GPL-licensed npm packages, creating legal liability.", "Formulate automated Dependency Scan Guardrails checking for CVE vulnerabilities and copyleft licenses.", "[INSERT DEPENDENCY MANIFEST (package.json / pom.xml)]", ["1. License & Security Risk Audit", "2. Blocked License List", "3. Automated PR Bot Remediation Strategy"]),
        ("Prompt 82: Feature Flag Architecture & Progressive Rollout Plan", "Release Engineering Lead", "Big-bang feature releases cause widespread production incidents that are difficult to rollback.", "Architect a LaunchDarkly / Unleash feature flag system supporting Canary and Blue-Green rollouts.", "[INSERT NEW FEATURE CODE MODULE & USER TARGETING]", ["1. Feature Flag Naming & Scope Schema", "2. Progressive Rollout Schedule (1% -> 10% -> 100%)", "3. Automated Kill-Switch Protocol"]),
        ("Prompt 83: Legacy Monolith Strangler Fig Pattern Migration Plan", "Enterprise Application Modernization Lead", "Core billing functionality is locked inside a 15-year-old COBOL/Java monolith.", "Design a Strangler Fig migration strategy to incrementally carve out microservices without downtime.", "[INSERT MONOLITH SYSTEM SPECIFICATIONS]", ["1. Monolith Interception Point Map", "2. Intermediary API Gateway Architecture", "3. Multi-Phase Migration Schedule"]),
        ("Prompt 84: AI Code Generation Safety & Review Guardrails", "AI Engineering Lead", "Engineers copy-paste AI-generated code containing subtle memory leaks and security vulnerabilities.", "Formulate an AI-Generated Code Review Policy and automated inspection prompt.", "[INSERT AI GENERATED CODE EXCERPT]", ["1. Vulnerability & Leak Assessment", "2. Refactored Production Code", "3. Squad Verification Protocol"])
    ]),
    ("A.5 Enterprise Executive Leadership & VSM Officers (Prompts 85 - 105)", [
        ("Prompt 85: Board-Level Agile Transformation Progress Dashboard", "Chief Transformation Officer", "The Board demands a succinct quarterly progress report on the $50M digital transformation initiative.", "Synthesize organization-wide telemetry into a C-Suite metric dashboard focusing on ROI, Speed, and Quality.", "[INSERT ORG-WIDE METRICS & FINANCIAL EXPENDITURE]", ["1. Board-Level Executive Summary", "2. Key Metric Scorecard (Flow, Lead Time, Defect Rate)", "3. Strategic Value Delivered & Next Objectives"]),
        ("Prompt 86: Agile Capitalization Accounting (CapEx vs OpEx) Classifier", "Enterprise Controller & Finance Director", "Financial auditors struggle to categorize agile software development labor into CapEx vs OpEx under GAAP/IFRS.", "Establish an automated CapEx/OpEx labor classification framework based on Jira issue types and feature stages.", "[INSERT AGILE WORKFLOW STATES & ISSUE TYPES]", ["1. GAAP/IFRS Agile CapEx Rule Matrix", "2. Jira Field Mapping Schema", "3. Automated Audit Evidence Report Template"]),
        ("Prompt 87: M&A Technical & Operational Due Diligence Audit", "Corporate Development Tech Advisor", "The enterprise is acquiring a tech startup and needs to evaluate software technical debt and agile culture.", "Conduct a technical and operational due diligence assessment across Codebase, Architecture, Pipeline, and Team.", "[INSERT ACQUISITION TARGET ARCHITECTURE & CODE METRICS]", ["1. Technical Debt & Risk Scorecard", "2. Architecture Scalability Audit", "3. Post-Acquisition Integration Blueprint"]),
        ("Prompt 88: Enterprise Regulatory Audit (SOX/HIPAA/GDPR) Evaluator", "Head of Regulatory Compliance", "Regulatory bodies require proof of segregation of duties and change control compliance in automated pipelines.", "Build a Compliance Control Matrix mapping SOX/GDPR rules directly to automated CI/CD and deployment logs.", "[INSERT REGULATORY COMPLIANCE MANDATES]", ["1. Regulatory Mapping Grid", "2. Automated Compliance Evidence Pipeline", "3. Audit Defensibility Checklist"]),
        ("Prompt 89: Value Stream Flow Efficiency & Economic Loss Modeler", "Head of Value Stream Management", "Wait times account for 85% of total feature cycle time, causing massive hidden economic loss.", "Calculate Value Stream Flow Efficiency (Active Time / Total Cycle Time) and model annual economic savings.", "[INSERT VALUE STREAM TIMING METRICS]", ["1. Flow Efficiency Percentage Score", "2. Economic Loss Calculation (Cost of Waiting)", "3. Targeted Queue Elimination Strategy"]),
        ("Prompt 90: Strategic Resource Re-allocation & Capacity Forecasting", "VP of Workforce Planning", "Market changes require shifting 200 software engineers from legacy systems to new AI product lines.", "Model engineering capacity, skill transferability, and resource allocation across strategic initiatives.", "[INSERT CURRENT CAPACITY & TARGET PRODUCT HEADCOUNT]", ["1. Resource Re-allocation Matrix", "2. Skill Transition Friction Analysis", "3. 90-Day Workforce Migration Plan"]),
        ("Prompt 91: Talent Retention, Burnout Index & Workplace Health Audit", "Chief Human Resources Officer (CHRO)", "Engineering attrition has reached 22% due to crunch cycles, release anxiety, and operational toil.", "Analyze employee engagement data and on-call paging frequency to score Team Burnout Risk.", "[INSERT ATTRITION DATA, ON-CALL LOGS & SURVEYS]", ["1. Squad Burnout Index Heatmap", "2. Primary Workload Friction Drivers", "3. CHRO Retention & Work-Life Interventions"]),
        ("Prompt 92: Customer Lifetime Value (CLV) & NPS Telemetry Analyzer", "Chief Customer Officer (CCO)", "Product updates correlate with fluctuating Net Promoter Scores (NPS) and customer renewal rates.", "Correlate feature release telemetry with NPS, CLV, and customer churn metrics.", "[INSERT RELEASE DATES, NPS SCORES & CLV DATA]", ["1. Feature Impact Correlation Summary", "2. High-Value Customer Retention Drivers", "3. Product Strategy Adjustments"]),
        ("Prompt 93: Market Disruption & VUCA Competitive Scenario Simulator", "Chief Strategy Officer (CSO)", "A new disruptive competitor has launched a free AI-powered alternative to our core product.", "Simulate 3 strategic response scenarios (Price Pivot, Feature Leapfrog, Ecosystem Acquisition) using VUCA principles.", "[INSERT COMPETITOR PRODUCT ANNOUNCEMENT & MARKET METRICS]", ["1. Competitive Threat Assessment", "2. 3 Strategic Scenario Options", "3. Recommended 90-Day Execution Response"]),
        ("Prompt 94: Enterprise Generative AI ROI & Productivity Auditor", "Chief Technology Officer (CTO)", "The enterprise invested $5M in GitHub Copilot licenses and needs empirical proof of productivity gain.", "Evaluate developer throughput, code quality, DORA metrics, and developer satisfaction post-AI adoption.", "[INSERT PRE & POST AI ADOPTION METRICS]", ["1. Empirical ROI Scorecard", "2. Developer Productivity Delta (% change)", "3. License Optimization & Expansion Strategy"]),
        ("Prompt 95: Supply Chain & Third-Party Vendor Agile SLA Diagnostic", "VP of Global Procurement", "Key offshore vendors miss milestone deliverables while claiming 100% agile sprint completion.", "Audit vendor velocity metrics, defect leakage, and deliverable quality against SLA terms.", "[INSERT VENDOR SPRINT REPORTS & DEFECT LOGS]", ["1. Vendor Performance Audit Grid", "2. SLA Discrepancy Identification", "3. Remediation & Contract Enforcement Strategy"]),
        ("Prompt 96: Enterprise Knowledge Graph & Org Network Mapper", "Chief Information Officer (CIO)", "Informal communication networks drive critical technical decisions, creating organizational blind spots.", "Analyze Slack/Jira interaction patterns to build an Organizational Network Analysis (ONA) graph.", "[INSERT ANONYMIZED TOOL INTERACTION LOGS]", ["1. ONA Key Information Hubs & Bottlenecks", "2. Knowledge Silo Identification", "3. Structural Communication Optimization"]),
        ("Prompt 97: Sustainability, ESG & Green Computing Tech Stack Audit", "Head of Corporate Sustainability", "Cloud data center carbon footprint must be reduced by 30% to meet corporate ESG targets.", "Audit server compute utilization, compute architecture, and waste to design a Green Computing Plan.", "[INSERT CLOUD COMPUTE USAGE & CARBON INTENSITY DATA]", ["1. Carbon Emissions Tech Audit", "2. Green Computing Optimization Strategy", "3. ESG Reporting Metric Integration"]),
        ("Prompt 98: Executive Succession & Leadership Capability Pipeline", "Chief Executive Officer (CEO)", "Leadership lacks qualified internal candidates to step into VP and Director technology roles.", "Evaluate senior agile coaches and engineering managers against an Executive Leadership Competency Framework.", "[INSERT CANDIDATE PERFORMANCE & LEADERSHIP EVALUATIONS]", ["1. Leadership Capability Grid", "2. Succession Readiness Ranking", "3. Executive Mentorship & Growth Roadmap"]),
        ("Prompt 99: Crisis Management & Business Continuity Execution Script", "Chief Risk Officer (CRO)", "A major ransomware attack has encrypted core data centers, requiring immediate emergency failover.", "Execute an Enterprise Crisis Command Protocol defining communication roles, recovery priorities, and stakeholder updates.", "[INSERT INCIDENT DETAILS & SYSTEM IMPACT]", ["1. Crisis Command Structure", "2. Priority System Recovery Order", "3. Executive & Public Communication Scripts"]),
        ("Prompt 100: Global Cross-Timezone Agile Operations Blueprint", "VP of Global Operations", "Engineering squads distributed across Americas, Europe, and Asia suffer from 24-hour handoff delays.", "Architect a Follow-the-Sun asynchronous agile workflow model with clear handoff protocols.", "[INSERT REGIONAL TEAM SIZES & TIMEZONE COVERAGE]", ["1. Follow-the-Sun Handoff Schema", "2. Asynchronous Governance Protocols", "3. Cross-Region Tool Integration Strategy"]),
        ("Prompt 101: Data Governance & Master Data Alignment Blueprint", "Chief Data Officer (CDO)", "Data silos across business units result in contradictory financial and customer reporting metrics.", "Design an Enterprise Master Data Management (MDM) governance framework aligned with Agile Data Mesh principles.", "[INSERT DATA DOMAIN SPECS & REPORTING DISCREPANCIES]", ["1. Data Mesh Governance Blueprint", "2. Domain Ownership Schema", "3. Master Data Harmonization Plan"]),
        ("Prompt 102: Enterprise DevOps Pipeline Standardization Framework", "VP of Platform Engineering", "Fifty different engineering squads maintain 50 custom deployment scripts, creating security vulnerabilities.", "Specify an Enterprise Internal Developer Platform (IDP) Golden Path deployment pipeline.", "[INSERT SQUAD TOOLING VARIATIONS & PIPELINE LOGS]", ["1. IDP Golden Path Pipeline Blueprint", "2. Standardized Tool Stack Definition", "3. Migration & Adoption Strategy"]),
        ("Prompt 103: Workforce Upskilling & AI Literacy Certification Framework", "Head of Learning & Development", "The company needs 5,000 non-technical employees to become proficient in AI prompt engineering and automation.", "Design a tiered Enterprise AI Literacy Certification Program (Bronze, Silver, Gold).", "[INSERT TARGET EMPLOYEE DEMOGRAPHICS & GOALS]", ["1. Tiered Curriculum Blueprint", "2. Practical Assessment Criteria", "3. Certification & Gamification Strategy"]),
        ("Prompt 104: Strategic Vendor Negotiation & Agile Contract Template", "Head of Procurement", "The company is negotiating a $20M multi-year cloud and software consulting contract.", "Draft an outcome-linked Vendor Contract Template with risk-sharing penalty/bonus clauses.", "[INSERT VENDOR SCOPE & PROPOSED PRICING]", ["1. Outcome-Linked Contract Clauses", "2. Risk-Sharing Bonus/Penalty Grid", "3. SLA Audit Mechanism"]),
        ("Prompt 105: AI Augmented Enterprise Agile Transformation Assessment", "Chief Transformation Officer", "The enterprise has completed a 2-year AI and Agile transformation and requires a final evaluation.", "Conduct an exhaustive assessment of transformation achievements against original business case goals.", "[INSERT ORIGINAL BUSINESS CASE & FINAL METRICS]", ["1. Final Transformation Scorecard", "2. Business Case ROI Delta", "3. Continuous Evolution Recommendations"])
    ])
]

prompt_counter = 1
for cat_title, prompts in categories:
    appA_content.append(f'\n## {cat_title}\n')
    for title, persona, context, task, params, outputs in prompts:
        appA_content.append(f'### {title}')
        appA_content.append(f'**System Persona**: {persona}')
        appA_content.append(f'**Context Boundary**: {context}')
        appA_content.append(f'**Core Task Specification**: {task}')
        appA_content.append(f'**Template Parameters**: `{params}`')
        appA_content.append('**Required Output Schema**:')
        for out_item in outputs:
            appA_content.append(f'- {out_item}')
        appA_content.append('')
        prompt_counter += 1

with open(APP_A_PATH, 'w', encoding='utf-8') as f:
    f.write('\n'.join(appA_content))

print(f'Generated {APP_A_PATH} with {prompt_counter-1} prompts.')

# Generate Appendix B
appB_content = []
appB_content.append('# Appendix B: Enterprise JQL, WIQL & AQL Cheat Sheet\n')
appB_content.append('📌 EXECUTIVE COACHING GUARDRAIL: Complete Syntax Reference for Jira JQL, Azure DevOps WIQL & Assets AQL\n')
appB_content.append('This operational syntax reference provides exhaustive query patterns, field definitions, function libraries, and production-tested query templates for Atlassian Jira Query Language (JQL), Azure DevOps Work Item Query Language (WIQL), and Atlassian Assets Query Language (AQL).\n')

appB_content.append('## B.1 Jira Query Language (JQL) Master Reference\n')
appB_content.append('JQL is a flexible SQL-like syntax used to query issues across Jira Data Center and Jira Cloud. Standard clause structure follow: `[Field] [Operator] [Value/Function] [ORDER BY Field ASC|DESC]`.\n')

appB_content.append('### JQL Operators Reference')
appB_content.append('| Operator | Description | Example Syntax |')
appB_content.append('| --- | --- | --- |')
appB_content.append('| `=` | Exact equality match | `project = "PAYMENTS"` |')
appB_content.append('| `!=` | Inequality match | `status != "Closed"` |')
appB_content.append('| `>` / `>=` | Greater than (dates/numbers) | `created >= "-7d"` |')
appB_content.append('| `<` / `<=` | Less than (dates/numbers) | `storyPoints <= 5` |')
appB_content.append('| `IN` | Matches any value in set | `status IN ("In Progress", "In Review")` |')
appB_content.append('| `NOT IN` | Excludes all values in set | `priority NOT IN ("Low", "Trivial")` |')
appB_content.append('| `~` | Fuzzy text search (contains) | `summary ~ "authentication failure"` |')
appB_content.append('| `!~` | Fuzzy text exclusion | `description !~ "deprecated"` |')
appB_content.append('| `IS EMPTY` | Field contains null/no value | `"Epic Link" IS EMPTY` |')
appB_content.append('| `IS NOT EMPTY` | Field contains valid value | `"Sprint" IS NOT EMPTY` |')
appB_content.append('| `WAS` | Historical status match | `status WAS "In Progress"` |')
appB_content.append('| `WAS IN` | Historical status set match | `status WAS IN ("Blocked", "Testing")` |')
appB_content.append('| `CHANGED` | Status/field change event | `status CHANGED DURING ("2026-01-01", "2026-03-31")` |')

appB_content.append('\n### JQL Built-in Functions Library')
appB_content.append('| Function Name | Return Type | Description & Usage |')
appB_content.append('| --- | --- | --- |')
appB_content.append('| `currentUser()` | User ID | Evaluates to logged-in user: `assignee = currentUser()` |')
appB_content.append('| `membersOf("group")` | Group Users | Matches members of group: `assignee IN membersOf("jira-coaches")` |')
appB_content.append('| `openSprints()` | Sprint IDs | Active open sprints: `sprint IN openSprints()` |')
appB_content.append('| `closedSprints()` | Sprint IDs | Completed sprints: `sprint IN closedSprints()` |')
appB_content.append('| `futureSprints()` | Sprint IDs | Planned future sprints: `sprint IN futureSprints()` |')
appB_content.append('| `startOfDay(inc)` | Date | Beginning of day: `created >= startOfDay("-30d")` |')
appB_content.append('| `endOfDay(inc)` | Date | End of day timestamp: `updated <= endOfDay()` |')
appB_content.append('| `startOfWeek()` | Date | First day of current week: `resolved >= startOfWeek()` |')
appB_content.append('| `startOfMonth()` | Date | First day of current month: `created >= startOfMonth()` |')
appB_content.append('| `issueHistory()` | Issue Keys | Issues recently viewed by user: `id IN issueHistory()` |')
appB_content.append('| `watchedIssues()` | Issue Keys | Issues watched by user: `id IN watchedIssues()` |')

appB_content.append('\n### 20 Production-Tested Enterprise JQL Query Templates')
appB_content.append('| Query ID | Operational Objective | Exact JQL Syntax Template |')
appB_content.append('| --- | --- | --- |')
appB_content.append('| JQL-01 | Unresolved Overdue Epics | `project = "CORE" AND issueType = Epic AND statusCategory != Done AND due < "0d" ORDER BY due ASC` |')
appB_content.append('| JQL-02 | Stale Work Items Stuck in Active Sprint | `sprint IN openSprints() AND updated < -3d AND statusCategory = "In Progress"` |')
appB_content.append('| JQL-03 | Orphaned Stories Missing Epic Links | `project = "PAY" AND issueType = Story AND "Epic Link" IS EMPTY AND statusCategory != Done` |')
appB_content.append('| JQL-04 | Currently Blocked High-Priority Items | `priority IN ("Highest", "High") AND status = "Blocked" AND statusCategory != Done` |')
appB_content.append('| JQL-05 | Sprint Spillover Work Items | `sprint IN openSprints() AND sprint IN closedSprints()` |')
appB_content.append('| JQL-06 | Bugs Escaped to Production | `issueType = Bug AND Environment = "Production" AND created >= startOfMonth()` |')
appB_content.append('| JQL-07 | High Cost-of-Delay Unassigned Items | `assignee IS EMPTY AND priority = "Highest" AND statusCategory != Done ORDER BY created ASC` |')
appB_content.append('| JQL-08 | Items Pending Code Review > 48 Hours | `status = "In Review" AND status CHANGED TO "In Review" BEFORE -48h` |')
appB_content.append('| JQL-09 | Scope Creep Added Mid-Sprint | `sprint IN openSprints() AND issueFunction IN addedAfterSprintStart()` |')
appB_content.append('| JQL-10 | Epics Missing Target Quarter End Date | `issueType = Epic AND "Target End" IS EMPTY AND statusCategory != Done` |')
appB_content.append('| JQL-11 | Stories Sliced Too Large (>8 Points) | `issueType = Story AND "Story Points" > 8 AND statusCategory != Done` |')
appB_content.append('| JQL-12 | Security Vulnerability Escalations | `issueType = Vulnerability AND "CVSS Score" >= 7.0 AND status != Closed` |')
appB_content.append('| JQL-13 | Cross-Project Dependency Blockers | `issueInLinkedIssuesByRelation("is blocked by") AND statusCategory != Done` |')
appB_content.append('| JQL-14 | Completed Items Pending Documentation | `status = "Done" AND "Doc Status" != "Published" AND resolved >= startOfWeek()` |')
appB_content.append('| JQL-15 | Unestimated Backlog Refinement Candidates | `project = "MOBILE" AND "Story Points" IS EMPTY AND status = "Refinement"` |')
appB_content.append('| JQL-16 | QA Testing Rejection Recycling | `status CHANGED FROM "In QA" TO "In Progress" GREATER THAN 2` |')
appB_content.append('| JQL-17 | Architecture Spike Decision Pending | `issueType = Spike AND statusCategory != Done AND updated < -5d` |')
appB_content.append('| JQL-18 | Customer Support Escalated Defect | `labels IN ("support-escalation", "vip-customer") AND statusCategory != Done` |')
appB_content.append('| JQL-19 | Capitalizable Epic Engineering Labor | `issueType = Epic AND "CapEx Status" = "Approved" AND statusCategory = "In Progress"` |')
appB_content.append('| JQL-20 | Quarterly Release Readiness Gate | `fixVersion = "2026.Q1" AND statusCategory != Done AND "QA Approval" IS EMPTY` |')

appB_content.append('\n## B.2 Azure DevOps Work Item Query Language (WIQL) Master Reference\n')
appB_content.append('WIQL syntax structures: `SELECT [System.Field] FROM WorkItems WHERE [Condition] ORDER BY [Field]`.\n')

appB_content.append('### WIQL Field Schemas & Operators')
appB_content.append('| WIQL Field Name | Data Type | Operational Description |')
appB_content.append('| --- | --- | --- |')
appB_content.append('| `System.Id` | Integer | Unique work item identifier |')
appB_content.append('| `System.WorkItemType` | String | Epic, Feature, User Story, Task, Bug |')
appB_content.append('| `System.State` | String | New, Active, Resolved, Closed, Removed |')
appB_content.append('| `System.AssignedTo` | User | Current assignee identity |')
appB_content.append('| `System.AreaPath` | Path | Organizational area hierarchy path |')
appB_content.append('| `System.IterationPath` | Path | Sprint/Iteration sprint timeline path |')
appB_content.append('| `Custom.Blocked` | Boolean | True/False flag indicating active impediment |')
appB_content.append('| `Microsoft.VSTS.Scheduling.StoryPoints` | Double | Numerical story point estimate |')

appB_content.append('\n### 15 Production WIQL Query Templates')
appB_content.append('| Query ID | Objective | WIQL Query Syntax |')
appB_content.append('| --- | --- | --- |')
appB_content.append('| WIQL-01 | Blocked Active Work Items | `SELECT [System.Id], [System.Title] FROM WorkItems WHERE [System.State] = \'Active\' AND [Custom.Blocked] = \'True\'` |')
appB_content.append('| WIQL-02 | Unassigned High Priority Bugs | `SELECT [System.Id], [System.Title] FROM WorkItems WHERE [System.WorkItemType] = \'Bug\' AND [System.AssignedTo] = \'\' AND [Microsoft.VSTS.Common.Priority] = 1` |')
appB_content.append('| WIQL-03 | Active Stories Missing Iteration | `SELECT [System.Id], [System.Title] FROM WorkItems WHERE [System.WorkItemType] = \'User Story\' AND [System.IterationPath] UNDER \'Project\\Backlog\'` |')
appB_content.append('| WIQL-04 | Stale In-Progress Tasks | `SELECT [System.Id], [System.Title] FROM WorkItems WHERE [System.State] = \'Active\' AND [System.ChangedDate] < @today - 5` |')
appB_content.append('| WIQL-05 | Current Iteration Commitment | `SELECT [System.Id], [System.Title] FROM WorkItems WHERE [System.IterationPath] = @currentIteration AND [System.State] <> \'Closed\'` |')
appB_content.append('| WIQL-06 | Cross-Project Feature Dependencies | `SELECT [System.Id], [System.Title] FROM WorkItemLinks WHERE [Source].[System.WorkItemType] = \'Feature\' AND [System.Links.LinkType] = \'System.LinkTypes.Dependency-Forward\'` |')
appB_content.append('| WIQL-07 | PR Build Failure Escalations | `SELECT [System.Id], [System.Title] FROM WorkItems WHERE [System.Tags] CONTAINS \'build-failure\' AND [System.State] = \'Active\'` |')
appB_content.append('| WIQL-08 | High Effort Unsliced Features | `SELECT [System.Id] FROM WorkItems WHERE [System.WorkItemType] = \'Feature\' AND [Microsoft.VSTS.Scheduling.StoryPoints] > 20` |')
appB_content.append('| WIQL-09 | Production Security Patches | `SELECT [System.Id] FROM WorkItems WHERE [System.Tags] CONTAINS \'security\' AND [System.State] <> \'Closed\'` |')
appB_content.append('| WIQL-10 | Recently Closed User Stories | `SELECT [System.Id] FROM WorkItems WHERE [System.WorkItemType] = \'User Story\' AND [System.State] = \'Closed\' AND [System.ChangedDate] >= @today - 7` |')
appB_content.append('| WIQL-11 | Orphaned Tasks Without Parent | `SELECT [System.Id] FROM WorkItems WHERE [System.WorkItemType] = \'Task\' AND NOT ([System.Id] IN FROM WorkItemLinks WHERE [Target].[System.WorkItemType] = \'User Story\')` |')
appB_content.append('| WIQL-12 | CapEx Eligible Development | `SELECT [System.Id] FROM WorkItems WHERE [Custom.CapExApproved] = \'True\' AND [System.State] = \'Active\'` |')
appB_content.append('| WIQL-13 | SLA Breach Incident Tickets | `SELECT [System.Id] FROM WorkItems WHERE [System.WorkItemType] = \'Incident\' AND [Custom.SLABreach] = \'True\'` |')
appB_content.append('| WIQL-14 | User Stories Pending Acceptance | `SELECT [System.Id] FROM WorkItems WHERE [System.State] = \'Resolved\' AND [System.WorkItemType] = \'User Story\'` |')
appB_content.append('| WIQL-15 | Architectural Spikes | `SELECT [System.Id] FROM WorkItems WHERE [System.Tags] CONTAINS \'spike\' AND [System.State] = \'Active\'` |')

appB_content.append('\n## B.3 Atlassian Assets Query Language (AQL) Master Reference\n')
appB_content.append('AQL searches object schemas in Jira Service Management Assets (Insight CMDB). Syntax: `objectType = "Name" AND [attribute] [operator] [value]`.\n')

appB_content.append('### 15 Production AQL Query Templates')
appB_content.append('| Query ID | Operational Objective | Exact AQL Syntax Template |')
appB_content.append('| --- | --- | --- |')
appB_content.append('| AQL-01 | Degraded Production Applications | `objectType = "Application" AND Environment = "Production" AND Status = "Degraded"` |')
appB_content.append('| AQL-02 | Production Servers Past EOL | `objectType = "Host" AND Environment = "Production" AND "End of Life Date" < now()` |')
appB_content.append('| AQL-03 | High-Criticality Services | `objectType = "Business Service" AND Tier = "Tier 1" AND OperationalStatus = "Active"` |')
appB_content.append('| AQL-04 | Assets Linked to Open Major Incidents | `objectHaving(connectedTickets(status != "Closed" AND priority = "Highest"))` |')
appB_content.append('| AQL-05 | Unassigned Cloud Infrastructure Objects | `objectType = "AWS Instance" AND Owner IS EMPTY AND Environment = "Production"` |')
appB_content.append('| AQL-06 | Database Clusters Missing Backup | `objectType = "Database" AND "Backup Strategy" IS EMPTY AND Environment = "Production"` |')
appB_content.append('| AQL-07 | SSL Certificates Expiring < 30 Days | `objectType = "Certificate" AND "Expiration Date" <= 30d AND Status = "Active"` |')
appB_content.append('| AQL-08 | Microservices Managed by Squad X | `objectType = "Microservice" AND "Managing Team" = "Payments Squad"` |')
appB_content.append('| AQL-09 | Non-Compliant Software Licenses | `objectType = "Software License" AND "Compliance Status" = "Non-Compliant"` |')
appB_content.append('| AQL-10 | Production K8s Clusters Running Legacy K8s | `objectType = "Kubernetes Cluster" AND Version < "1.28" AND Environment = "Production"` |')
appB_content.append('| AQL-11 | Hardware Laptops Due Refresh | `objectType = "Laptop" AND "Purchase Date" <= -3y AND Status = "In Use"` |')
appB_content.append('| AQL-12 | API Endpoints Missing Owner Squad | `objectType = "API Endpoint" AND "Owner Squad" IS EMPTY` |')
appB_content.append('| AQL-13 | Critical Infra Impacted by Active RFC | `objectHaving(connectedTickets(issueType = "Change" AND status = "In Progress"))` |')
appB_content.append('| AQL-14 | Third-Party SaaS Vendors Facing Renewals | `objectType = "SaaS Product" AND "Renewal Date" <= 60d` |')
appB_content.append('| AQL-15 | Unmapped Security Assets | `objectType = "Security Gateway" AND "Architecture Domain" IS EMPTY` |')

with open(APP_B_PATH, 'w', encoding='utf-8') as f:
    f.write('\n'.join(appB_content))

print(f'Generated {APP_B_PATH}.')

# Generate Appendix C
appC_content = []
appC_content.append('# Appendix C: Enterprise Agile & AI Maturity Assessment Checklist\n')
appC_content.append('📌 EXECUTIVE COACHING GUARDRAIL: Comprehensive Operational Audit & Diagnostic Tool for Technology Leadership\n')
appC_content.append('This diagnostic audit tool enables technology executives, VSM officers, and enterprise agile coaches to evaluate organizational flow, governance automation, and AI adoption maturity across 35 criteria spanning 7 strategic pillars.\n')

appC_content.append('## C.1 Enterprise Governance, Flow & AI Maturity Matrix\n')

pillars = [
    ("Pillar 1: Strategic Alignment & Portfolio Governance", [
        ("1.1 OKR Line-of-Sight", "Do team backlogs directly map to empirical corporate OKRs?", "No OKRs exist; work is unplanned tactical noise.", "OKRs exist but act as feature checklists.", "Squad epics map to OKRs with quarterly reviews.", "Automated bi-directional line-of-sight telemetry.", "Real-time OKR outcome correlation via AI agents.", "Jira Align / ADO OKR link ratio > 90%"),
        ("1.2 Funding & Budgeting", "How is capital allocated to software development?", "Rigid annual project budgeting with fixed scope.", "Project budgets with mid-year change requests.", "Participatory budgeting per Value Stream.", "Dynamic guardrail funding re-allocated quarterly.", "Continuous AI flow-based capital allocation.", "Financial CapEx/OpEx automated audit logs"),
        ("1.3 Portfolio Prioritization", "How are portfolio initiatives ranked?", "HiPPO (Highest Paid Person's Opinion) decision.", "Basic ROI spreadsheets with political debate.", "Standardized WSJF / RICE scoring applied.", "Automated WSJF scoring linked to Cost of Delay.", "AI predictive ROI and WSJF portfolio engine.", "Portfolio WSJF adoption coverage 100%"),
        ("1.4 Capacity Allocation", "How is squad capacity split across competing priorities?", "100% focused on new features; debt ignored.", "Ad-hoc fix sprints when systems break.", "Defined ratio (e.g., 60% feature, 20% debt, 20% ops).", "Real-time capacity tracking via issue types.", "AI-driven dynamic capacity rebalancing.", "Jira/ADO Capacity distribution chart"),
        ("1.5 Executive Steering Cadence", "How does leadership inspect portfolio progress?", "Monthly 50-page PowerPoint status decks.", "Bi-weekly project manager status meetings.", "Monthly Lean Portfolio Management (LPM) reviews.", "Real-time automated executive dashboards.", "Continuous C-Suite AI metric synthesis.", "Zero manual PowerPoint status decks created")
    ]),
    ("Pillar 2: Value Stream Slicing & Backlog Quality", [
        ("2.1 Story Slicing", "How are features sliced for sprint execution?", "Monolithic 40-point epics pushed into sprints.", "Large stories (13-20 pts) spanning multiple sprints.", "Stories sliced into 1-3 day testable units (SPIDR).", "Automated story slicing recommendations.", "AI autonomous epic decomposition engine.", "Average Story Point size <= 3 points"),
        ("2.2 Acceptance Criteria", "How are acceptance criteria defined?", "Vague 1-line text descriptions or blank.", "Bullet points added mid-sprint by QA.", "Standardized Gherkin BDD Given-When-Then criteria.", "Automated BDD test scenario generation.", "AI real-time spec-to-test code synthesis.", "Gherkin coverage on backlog items > 95%"),
        ("2.3 Definition of Ready (DoR)", "What gates must work pass before sprint entry?", "No gating; raw customer requests pulled directly.", "Informal PO verbal approval.", "Strict DoR checklist enforced during refinement.", "Automated DoR validation bot in issue tracker.", "AI predictive story readiness scoring.", "DoR compliance rate 100%"),
        ("2.4 Definition of Done (DoD)", "When is a story considered complete?", "Code written on dev laptop.", "Merged to dev branch; QA untested.", "Complete DoD (Unit test, PR review, QA, Staging deploy).", "Automated DoD enforcement in CI/CD pipeline.", "Zero-touch automated release DoD verification.", "Pipeline automated DoD check pass rate 100%"),
        ("2.5 Backlog Refinement Pacing", "How healthily is the backlog maintained ahead of squads?", "Sprint planning is spent discovering user stories.", "1 sprint of unrefined stories ready.", "2-3 sprints of refined, estimated backlog ready.", "Automated backlog replenishment alerts.", "AI predictive backlog health maintenance.", "Refined backlog buffer >= 2.5 Sprints")
    ]),
    ("Pillar 3: Continuous Delivery & Pipeline Guardrails", [
        ("3.1 CI/CD Automation", "How are applications built and deployed?", "Manual FTP / SSH copy to production servers.", "Scripted local builds deployed manually.", "Fully automated CI/CD pipeline (Jenkins/GitHub Actions).", "Trunk-based development with auto-deploy to staging.", "Zero-touch continuous deployment to production.", "Deployment Frequency >= 5 per day"),
        ("3.2 Automated Testing", "What is the depth of automated test coverage?", "100% manual QA regression testing.", "Basic unit tests (<30% coverage).", "Comprehensive unit, integration, and E2E automation (>80%).", "Automated pipeline test impact analysis.", "AI self-healing test scripts & generation.", "Automated test code coverage >= 85%"),
        ("3.3 DevSecOps Security Gates", "How are security vulnerabilities intercepted?", "Annual manual penetration testing.", "Manual code security reviews prior to release.", "Automated SAST, DAST, and SCA pipeline gates.", "Zero-trust automated policy enforcement.", "AI real-time vulnerability patch generation.", "Zero critical CVEs in production pipelines"),
        ("3.4 Infrastructure-as-Code (IaC)", "How is cloud infrastructure provisioned?", "Manual AWS/Azure console clicking.", "Ad-hoc shell scripts for server setup.", "100% IaC (Terraform, CloudFormation, Ansible).", "Automated IaC security scan & drift detection.", "AI autonomous cloud infra optimization.", "IaC provisioning coverage 100%"),
        ("3.5 Release Strategy", "How are new features delivered to end users?", "Big-bang weekend maintenance downtime releases.", "Scheduled night releases with manual rollback.", "Blue-Green / Canary releases with feature flags.", "Automated progressive rollouts & kill-switches.", "AI autonomous release risk evaluation.", "Production release downtime = 0 minutes")
    ]),
    ("Pillar 4: Flow Telemetry & Quantitative Metrics", [
        ("4.1 Cycle Time & Lead Time", "How fast does an idea reach production?", "Lead time > 180 days; unmeasured.", "Lead time 60-90 days; manually tracked in Excel.", "Lead time < 14 days tracked automatically in Jira/ADO.", "Flow Lead Time < 5 days measured in real-time.", "AI lead time anomaly prediction & interception.", "Mean Cycle Time <= 3.5 Days"),
        ("4.2 Flow Efficiency", "What ratio of cycle time is active work vs waiting?", "Flow Efficiency < 5% (95% wait time).", "Flow Efficiency 5-10%.", "Flow Efficiency 15-25% tracked via VSM tools.", "Flow Efficiency > 35% with queue alerts.", "AI active queue elimination engine (>50%).", "Flow Efficiency Index >= 35%"),
        ("4.3 Work-in-Progress (WIP)", "How effectively is concurrent work controlled?", "Unbounded WIP; developers work on 5+ stories at once.", "Soft WIP limits frequently ignored.", "Strict Kanban WIP limits enforced per stage.", "Automated WIP violation pipeline blocks.", "AI dynamic swarming & WIP optimization.", "Average WIP per Developer <= 1.5"),
        ("4.4 Escaped Defect Rate", "How many bugs reach production customers?", "High defect leakage (>20% of release items).", "Defect rate 10-20% requiring emergency patches.", "Escaped defect rate < 5% tracked per sprint.", "Automated defect origin attribution.", "AI predictive bug prevention in PR review.", "Escaped Defect Rate < 2.0%"),
        ("4.5 DORA Metrics Instrumentation", "How is DevOps performance measured?", "No DORA metrics collected.", "DORA metrics manually calculated quarterly.", "Automated real-time DORA dashboard (Four Keys).", "DORA Elite Performer status verified.", "AI autonomous DORA optimization engine.", "DORA Elite performance classification")
    ]),
    ("Pillar 5: AI Co-Pilot Integration & Automation", [
        ("5.1 Developer AI Assistant", "How do developers utilize AI coding tools?", "AI tools banned by IT security.", "Ad-hoc personal ChatGPT usage.", "Enterprise GitHub Copilot / Cursor deployed.", "Custom MCP server integration for internal APIs.", "Autonomous AI agent pair programming.", "Copilot adoption rate > 80%"),
        ("5.2 Agile Coaching AI Co-Pilot", "How do coaches and POs leverage AI?", "Manual creation of all agile artifacts.", "Basic ChatGPT prompt usage for story writing.", "Custom RAG AI Co-Pilot trained on internal docs.", "MCP-connected AI agent automating ceremonies.", "Autonomous AI Agile Enterprise Co-Pilot.", "AI Coaching Co-Pilot active daily usage"),
        ("5.3 AI Governance & Guardrails", "How is AI usage governed and audited?", "No policy; enterprise data risk unmonitored.", "Basic word document policy distributed.", "Automated AI data loss prevention (DLP) gates.", "Real-time AI prompt audit logging & compliance.", "Autonomous AI model safety monitoring.", "Zero data leak incidents via AI tools"),
        ("5.4 Retrieval-Augmented Generation", "How is enterprise domain knowledge accessed?", "Knowledge trapped in employee heads & email.", "Scattered Confluence pages with poor search.", "Enterprise RAG knowledge base connected to vector DB.", "Real-time auto-updating RAG pipeline from code/Jira.", "Self-learning enterprise knowledge graph.", "RAG query retrieval accuracy > 90%"),
        ("5.5 Automated Test Generation", "How are test cases created using AI?", "Manual test writing by QA engineers.", "AI used to draft basic unit test templates.", "Automated PR-triggered AI unit & integration test gen.", "AI spec-to-executable test suite generation.", "Autonomous AI test suite optimization.", "AI-generated test coverage ratio > 40%")
    ]),
    ("Pillar 6: Organizational Culture & Psychological Safety", [
        ("6.1 Psychological Safety", "Can team members speak up and report failures?", "Blame culture; failures punished publicly.", "Mistakes tolerated quietly; risks hidden.", "Blameless retrospectives & post-mortems standard.", "Psychological safety survey index measured quarterly.", "Continuous blameless organizational culture.", "Psychological Safety Score >= 4.2 / 5.0"),
        ("6.2 Team Autonomy", "How much authority do squads have over execution?", "Micro-managed by managers assigning tasks daily.", "Squads pick tasks but must seek approval for technical choices.", "Self-organizing squads with clear boundaries.", "Fully autonomous stream-aligned squads.", "Autonomous squads driving continuous innovation.", "Squad autonomy satisfaction index > 85%"),
        ("6.3 Learning & Experimentation", "How is continuous learning encouraged?", "Zero time allocated; 100% utilization demanded.", "Ad-hoc hackathons once a year.", "Dedicated 10% Innovation time (e.g., Hack Fridays).", "Continuous Kaizen experimentation canvas in sprints.", "AI-personalized learning & reskilling paths.", "Experimentation velocity >= 2 per squad/sprint"),
        ("6.4 Cross-Functional Collaboration", "How do business, dev, and ops work together?", "Siloed handoffs between Biz -> Dev -> QA -> Ops.", "PO sits with dev, but QA and Ops are separate.", "Cross-functional squads (PO, Dev, QA, DevSecOps).", "Stream-aligned team topologies with seamless interaction.", "Unified business-technology value engine.", "Cross-functional squad composition 100%"),
        ("6.5 Attrition & Work-Life Balance", "What is the sustainable pace of execution?", "High burnout (>20% annual attrition); crunch standard.", "Frequent overtime at sprint end.", "Sustainable pace enforced; overtime rare.", "Proactive burnout index monitoring via telemetry.", "Thriving engineering workplace culture.", "Annual Voluntary Tech Attrition < 5.0%")
    ]),
    ("Pillar 7: Governance, Risk & Regulatory Compliance", [
        ("7.1 Automated Regulatory Evidence", "How is compliance evidence gathered for auditors?", "Manual screenshot collection prior to audit.", "Scripts pulling logs into shared folders.", "Automated CI/CD compliance log aggregation.", "Real-time automated audit evidence pipeline.", "Continuous AI audit defense & compliance mapping.", "Zero audit finding non-conformances"),
        ("7.2 Change Approval Board (CAB)", "How are production changes authorized?", "Weekly manual CAB meeting reviewing 100 changes.", "CAB reviews high-risk changes only.", "Automated pipeline CAB approval for low-risk changes.", "CAB eliminated; 100% peer review + automated gates.", "AI real-time change risk scoring & instant approval.", "Manual CAB approval queue volume = 0"),
        ("7.3 Segregation of Duties", "How is developer self-approval prevented securely?", "Manual manager sign-off emails.", "Branch protection rules in GitHub/Bitbucket.", "Automated peer review + automated pipeline gate validation.", "Cryptographically signed build provenance (SLSA Level 3).", "AI immutable audit chain verification.", "SLSA Level 3 compliance verified"),
        ("7.4 Vendor & Partner Alignment", "How are external vendor teams governed?", "Fixed-price waterfall contracts creating conflict.", "Time-and-materials contracts with manual timesheets.", "Agile SOWs with joint outcome SLAs.", "Automated vendor telemetry integration in Jira.", "AI real-time vendor performance correlation.", "Agile SOW contract alignment 100%"),
        ("7.5 Disaster Recovery & Resilience", "How is system resilience verified?", "Untested disaster recovery documentation.", "Annual manual DR failover simulation.", "Automated multi-region cloud failover tests.", "Continuous Chaos Engineering in staging/prod.", "AI autonomous system self-healing & failover.", "Recovery Time Objective (RTO) < 60 seconds")
    ])
]

for p_title, criteria in pillars:
    appC_content.append(f'\n### {p_title}')
    appC_content.append('| Ref # & Criterion | Diagnostic Question | Level 1: Ad-Hoc | Level 2: Reactive | Level 3: Defined | Level 4: Measured | Level 5: Optimized / AI | Target Evidence Indicator |')
    appC_content.append('| --- | --- | --- | --- | --- | --- | --- | --- |')
    for ref, q, l1, l2, l3, l4, l5, ev in criteria:
        appC_content.append(f'| **{ref}** | {q} | {l1} | {l2} | {l3} | {l4} | {l5} | `{ev}` |')

appC_content.append('\n## C.2 Diagnostic Scoring & Assessment Rubric\n')
appC_content.append('To calculate an organization\'s Enterprise Flow & AI Maturity Index, evaluate all 35 criteria on a scale of 1 to 5 points (Total Possible Score: 175 Points).\n')

appC_content.append('| Score Band | Maturity Classification | Systemic Characteristics & Operational Reality | Recommended Strategic Transformation Blueprint |')
appC_content.append('| --- | --- | --- | --- |')
appC_content.append('| **35 - 60 Points** | **Band 1: Legacy Bureaucracy** | Severe friction, manual handoffs, high defect rates, long lead times (>90 days), zero AI adoption, high burnout. | Descale bureaucracy, eliminate manual CABs, implement basic CI/CD, establish pilot cross-functional squads. |')
appC_content.append('| **61 - 90 Points** | **Band 2: Transitional Agile** | Localized agile adoption in squads, siloed handoffs remain, partial CI/CD, ad-hoc AI usage, uncoordinated metrics. | Standardize DoD/DoR, institute Value Stream Mapping, deploy GitHub Copilot enterprise licenses, establish LPM. |')
appC_content.append('| **91 - 125 Points** | **Band 3: Defined Enterprise Flow** | Consistent sprint execution, 80%+ automated test coverage, real-time Jira/ADO telemetry, structured RAG AI usage. | Automate DevSecOps gates, establish DORA telemetry, deploy Model Context Protocol (MCP) AI agents, optimize WIP. |')
appC_content.append('| **126 - 155 Points** | **Band 4: Measured & Automated** | Continuous deployment, DORA High/Elite performance, automated compliance pipelines, AI Co-Pilots active across roles. | Implement Chaos Engineering, optimize Flow Efficiency (>35%), deploy autonomous AI code/test review agents. |')
appC_content.append('| **156 - 175 Points** | **Band 5: AI-Augmented Enterprise** | Zero-touch continuous delivery, AI-driven portfolio rebalancing, self-healing IT systems, predictive outcome analytics. | Institutionalize continuous AI innovation kata, mentor industry ecosystem, maintain generative AI guardrails. |')

with open(APP_C_PATH, 'w', encoding='utf-8') as f:
    f.write('\n'.join(appC_content))

print(f'Generated {APP_C_PATH}.')
