package com.securebank.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.MailException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    public void sendOtpEmail(String to, String customerName, String otp, String purpose) {
        String subject = "SecureBank - Your OTP for " + purpose;
        String content = "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden;'>"
                + "<div style='background-color: #001f3f; color: #FFD700; padding: 20px; text-align: center;'>"
                + "<h2>SecureBank</h2></div>"
                + "<div style='padding: 20px;'>"
                + "<p>Dear " + customerName + ",</p>"
                + "<p>Your One Time Password (OTP) for <strong>" + purpose + "</strong> is:</p>"
                + "<h1 style='text-align: center; color: #001f3f; font-size: 32px; letter-spacing: 5px;'>" + otp + "</h1>"
                + "<p>This OTP is valid for <strong>5 minutes</strong>. Please do not share it with anyone.</p>"
                + "</div>"
                + "<div style='background-color: #f4f4f4; padding: 10px; text-align: center; font-size: 12px;'>"
                + "If you did not request this, please contact support immediately."
                + "</div></div>";
        sendHtmlEmail(to, subject, content);
    }

    public void sendWelcomeEmail(String to, String customerName, String customerId, String accountNumber) {
        String subject = "Welcome to SecureBank";
        String content = "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden;'>"
                + "<div style='background-color: #001f3f; color: #FFD700; padding: 20px; text-align: center;'>"
                + "<h2>SecureBank</h2></div>"
                + "<div style='padding: 20px;'>"
                + "<p>Dear " + customerName + ",</p>"
                + "<p>Welcome to SecureBank! Your account has been successfully created.</p>"
                + "<p><strong>Customer ID:</strong> " + customerId + "</p>"
                + "<p><strong>Account Number:</strong> " + accountNumber + "</p>"
                + "<p>Thank you for banking with us.</p>"
                + "</div></div>";
        sendHtmlEmail(to, subject, content);
    }

    public void sendBillPaymentEmail(String to, String customerName, String billerName, java.math.BigDecimal amount, String status, String messageDetails) {
        String subject = "SecureBank AI - Bill Payment Notification: " + billerName;
        String headerBg = "SUCCESS".equalsIgnoreCase(status) ? "#001f3f" : "#991b1b";
        String statusColor = "SUCCESS".equalsIgnoreCase(status) ? "#4ade80" : "#f87171";
        
        String content = "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden;'>"
                + "<div style='background-color: " + headerBg + "; color: #FFD700; padding: 20px; text-align: center;'>"
                + "<h2>SecureBank AI Auto-Pay Agent</h2></div>"
                + "<div style='padding: 20px;'>"
                + "<p>Dear " + customerName + ",</p>"
                + "<p>" + messageDetails + "</p>"
                + "<div style='background:#f8fafc; padding:15px; border-radius:8px; margin:15px 0;'>"
                + "<p style='margin:5px 0;'><strong>Biller:</strong> " + billerName + "</p>"
                + "<p style='margin:5px 0;'><strong>Amount:</strong> $" + amount + "</p>"
                + "<p style='margin:5px 0;'><strong>Status:</strong> <span style='color:" + statusColor + "; font-weight:bold;'>" + status + "</span></p>"
                + "</div>"
                + "<p>Thank you for using SecureBank Agentic Banking Services.</p>"
                + "</div>"
                + "<div style='background-color: #f4f4f4; padding: 10px; text-align: center; font-size: 12px;'>"
                + "Automated message generated by SecureBank SmartBillSchedulerAgent."
                + "</div></div>";
        sendHtmlEmail(to, subject, content);
    }

    private void sendHtmlEmail(String to, String subject, String htmlContent) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setText(htmlContent, true);
            mailSender.send(message);
            log.info("Email sent successfully to {}", to);
        } catch (Exception e) {
            log.error("Failed to send email to {}: {}", to, e.getMessage());
        }
    }
}
