window.certificationsData = [
  {
    id: 'aigp',
    name: 'IAPP AIGP',
    fullTitle: 'Artificial Intelligence Governance Professional',
    authority: 'IAPP (International Association of Privacy Professionals)',
    category: 'AI Governance',
    badgeColor: '#8b5cf6',
    officialUrl: 'https://iapp.org/certify/aigp/',
    handbookUrl: 'https://iapp.org/store/books/aigp-body-of-knowledge/',
    prerequisites: 'No formal work experience prerequisite. Basic understanding of privacy principles (CIPP) or risk management recommended.',
    experienceRequired: '0 Years (Open to all)',
    examCost: '$550 USD (Exam fee) + $250 USD annual maintenance',
    examStructure: '90 Multiple Choice Questions | 2.5 Hours | Passing Score: 300/500 (Scale 100-500)',
    recertification: 'Requires 20 Continuing Privacy Education (CPE) credits every 2 years.',
    domains: [
      'Domain 1: Foundational AI Concepts & Machine Learning Lifecycle (15%)',
      'Domain 2: Global AI Laws & Regulations - EU AI Act, US State AI Laws, OECD Principles (30%)',
      'Domain 3: AI Risk Management Frameworks - NIST AI RMF, ISO 42001, ISO 31000 (25%)',
      'Domain 4: Ethical Principles, Transparency, Fairness & Algorithmic Accountability (15%)',
      'Domain 5: Establishing & Operationalizing Enterprise AI Governance Programs (15%)'
    ],
    description: 'The global gold standard credential for managing AI risks, ensuring compliance with the EU AI Act, and building enterprise AI governance frameworks.',
    careerRoles: ['Legal Counsel', 'Chief Privacy Officer (CPO)', 'AI Compliance Lead', 'AI Risk Officer', 'Governance Architect'],
    connectedTo: ['cipp', 'crisc'],
    connectionReason: 'Natural next step for CIPP holders to bridge data privacy into AI regulations, and for CRISC holders to operationalize AI risk management.'
  },
  {
    id: 'cissp',
    name: 'CISSP',
    fullTitle: 'Certified Information Systems Security Professional',
    authority: '(ISC)²',
    category: 'Cybersecurity',
    badgeColor: '#3b82f6',
    officialUrl: 'https://www.isc2.org/certifications/cissp',
    handbookUrl: 'https://www.isc2.org/exam-outline/cissp',
    prerequisites: '5 years of cumulative paid work experience in 2+ of the 8 (ISC)² domains. A 4-year college degree or approved credential waives 1 year.',
    experienceRequired: '5 Years Required (or Associate of (ISC)²)',
    examCost: '$749 USD',
    examStructure: '125-175 Computer Adaptive Testing (CAT) Questions | 3 Hours | Passing Score: 700/1000',
    recertification: '120 CPE credits over 3-year cycle + Annual Maintenance Fee ($125/yr).',
    domains: [
      'Domain 1: Security & Risk Management (15%)',
      'Domain 2: Asset Security (10%)',
      'Domain 3: Security Architecture & Engineering (13%)',
      'Domain 4: Communication & Network Security (13%)',
      'Domain 5: Identity & Access Management (IAM) (13%)',
      'Domain 6: Security Assessment & Testing (12%)',
      'Domain 7: Security Operations (13%)',
      'Domain 8: Software Development Security (11%)'
    ],
    description: 'The premier worldwide security credential validating leadership, technical architecture, and cybersecurity risk management capability.',
    careerRoles: ['CISO', 'Security Architect', 'IT Security Director', 'Cyber Risk Lead', 'Security Manager'],
    connectedTo: ['aaism'],
    connectionReason: 'Provides the core infrastructure security foundation required before advancing to ISACA AAISM (Advanced AI Security Management).'
  },
  {
    id: 'cipp',
    name: 'CIPP/E & CIPP/US',
    fullTitle: 'Certified Information Privacy Professional (Europe / US)',
    authority: 'IAPP',
    category: 'Privacy',
    badgeColor: '#06b6d4',
    officialUrl: 'https://iapp.org/certify/cippe/',
    handbookUrl: 'https://iapp.org/store/books/',
    prerequisites: 'No formal work experience prerequisite. Recommended familiarity with European/US privacy laws and legal compliance.',
    experienceRequired: '0 Years (Open to all)',
    examCost: '$550 USD',
    examStructure: '90 Multiple Choice Questions | 2.5 Hours | Passing Score: 300/500',
    recertification: '20 CPE credits every 2 years + IAPP Maintenance Fee.',
    domains: [
      'Domain 1: Introduction to European Data Protection Laws & Authorities (20%)',
      'Domain 2: European Data Protection Law - GDPR Principles & Legal Bases (35%)',
      'Domain 3: Data Subject Rights, Breach Notification & Accountability (25%)',
      'Domain 4: International Data Transfers, Third-Party Risk & Enforcement (20%)'
    ],
    description: 'The global benchmark credential for data privacy law, GDPR compliance enforcement, data protection officer (DPO) duties, and privacy program governance.',
    careerRoles: ['Data Protection Officer (DPO)', 'Privacy Attorney', 'Compliance Manager', 'Privacy Analyst'],
    connectedTo: ['aigp'],
    connectionReason: 'Forms the bedrock of data regulation knowledge required to evaluate AI training data rights and AI privacy impact.'
  },
  {
    id: 'crisc',
    name: 'CRISC',
    fullTitle: 'Certified in Risk and Information Systems Control',
    authority: 'ISACA',
    category: 'Risk Management',
    badgeColor: '#10b981',
    officialUrl: 'https://www.isaca.org/credentialing/crisc',
    handbookUrl: 'https://www.isaca.org/resources/crisc-review-manual',
    prerequisites: '3 years of cumulative work experience in IT risk management and IS control across at least 2 domains.',
    experienceRequired: '3 Years Required',
    examCost: '$575 (ISACA Members) / $760 (Non-members)',
    examStructure: '150 Multiple Choice Questions | 4 Hours | Passing Score: 450/800',
    recertification: '120 CPE credits over a 3-year cycle (minimum 20 CPEs annually).',
    domains: [
      'Domain 1: Governance & Enterprise Risk Management (26%)',
      'Domain 2: IT Risk Assessment & Threat Modeling (28%)',
      'Domain 3: Risk Response & Mitigation Controls (23%)',
      'Domain 4: Information Technology & Security Control Monitoring (23%)'
    ],
    description: 'The top-tier credential for assessing enterprise IT risks, designing internal controls, and implementing risk response frameworks.',
    careerRoles: ['Enterprise Risk Officer', 'IT Risk Analyst', 'Risk & Compliance Manager', 'Internal Auditor'],
    connectedTo: ['iso42001', 'aaia'],
    connectionReason: 'Equips risk managers with systemic evaluation skills needed to implement ISO 42001 AI management controls and AI audits.'
  },
  {
    id: 'iso42001',
    name: 'ISO/IEC 42001 Lead',
    fullTitle: 'ISO/IEC 42001 Lead Implementer / Auditor (AIMS)',
    authority: 'PECB / CQI IRCA / CertiProf',
    category: 'AI Governance',
    badgeColor: '#f59e0b',
    officialUrl: 'https://pecb.com/en/education-and-certification-for-individuals/iso-iec-42001',
    handbookUrl: 'https://www.iso.org/standard/81230.html',
    prerequisites: '3-5 years experience in IT governance, compliance, or ISO management systems (e.g. ISO 27001). Project log required.',
    experienceRequired: '3-5 Years Recommended',
    examCost: '$600 - $1,200 USD (Includes Training & Exam)',
    examStructure: '3 Hours Essay & Case Audit Exam | Verified Implementation/Audit Log',
    recertification: 'Annual surveillance requirement and audit log re-verification every 3 years.',
    domains: [
      'Domain 1: Context of the Organization & AI Management System Scope (Clause 4)',
      'Domain 2: Leadership, Policy & AI Governance Commitment (Clause 5)',
      'Domain 3: AI Risk Assessment & Impact Evaluation (Clause 6)',
      'Domain 4: Support & Technical Resource Management (Clause 7 & 8)',
      'Domain 5: AI Performance Evaluation, Auditing & Corrective Action (Clause 9 & 10)',
      'Domain 6: ISO 42001 Annex A Control Objectives (A.2 - A.10)'
    ],
    description: 'Formal international standard certification equipping practitioners to establish, implement, and audit enterprise AI Management Systems (AIMS).',
    careerRoles: ['AI Systems Lead', 'ISO Lead Auditor', 'Governance Consultant', 'Compliance Architect'],
    connectedTo: ['crisc', 'aigp'],
    connectionReason: 'Operationalizes high-level AI policy (AIGP) into measurable, auditable enterprise ISO standards.'
  },
  {
    id: 'aaism',
    name: 'ISACA AAISM',
    fullTitle: 'Advanced in AI Security Management',
    authority: 'ISACA',
    category: 'AI Security',
    badgeColor: '#ec4899',
    officialUrl: 'https://www.isaca.org/credentialing/advanced-in-ai-security-management',
    handbookUrl: 'https://www.isaca.org/resources/ai-security-framework',
    prerequisites: 'Recommended CISM or CISSP holding; 3-5 years experience in information security management.',
    experienceRequired: '3-5 Years Security Experience',
    examCost: '$575 (ISACA Members) / $760 (Non-members)',
    examStructure: 'Scenario-Based Multiple Choice | 3 Hours | Passing Score: 450/800',
    recertification: 'Annual CPE requirement tied to ISACA certification lifecycle.',
    domains: [
      'Domain 1: Adversarial Machine Learning Threat Vectors (25%)',
      'Domain 2: LLM Security & OWASP Top 10 for LLM Applications (30%)',
      'Domain 3: Model Inversion, Prompt Injection & Poisoning Countermeasures (25%)',
      'Domain 4: AI Supply Chain, Model Lineage & Third-Party Vendor Risk (20%)'
    ],
    description: 'Advanced technical credential for securing enterprise AI pipelines, fine-tuned LLM deployments, and mitigating adversarial machine learning threats.',
    careerRoles: ['AI Security Lead', 'CISO', 'DevSecOps Manager', 'Red Team Lead'],
    connectedTo: ['cissp'],
    connectionReason: 'Direct technical extension of CISSP into AI-specific threat defense and secure model lifecycle operations.'
  },
  {
    id: 'aaia',
    name: 'ISACA AAIA',
    fullTitle: 'Advanced in AI Audit',
    authority: 'ISACA',
    category: 'AI Audit',
    badgeColor: '#6366f1',
    officialUrl: 'https://www.isaca.org/credentialing/advanced-in-ai-audit',
    handbookUrl: 'https://www.isaca.org/resources/ai-audit-toolkit',
    prerequisites: 'Recommended CISA holding; 3+ years experience auditing IT and automated systems.',
    experienceRequired: '3+ Years Audit Experience',
    examCost: '$575 (ISACA Members) / $760 (Non-members)',
    examStructure: 'Scenario-Based Audit Exam | 3 Hours | Passing Score: 450/800',
    recertification: 'Annual CPE requirement tied to ISACA certification lifecycle.',
    domains: [
      'Domain 1: Algorithmic Bias, Disparate Impact & Fairness Auditing (30%)',
      'Domain 2: Training Data Lineage, Provenance & Quality Verification (25%)',
      'Domain 3: Explainability, SHAP/LIME Interpretability & Transparency (25%)',
      'Domain 4: Automated System Compliance & Continuous Model Auditing (20%)'
    ],
    description: 'Specialized certification for auditing complex AI algorithms, evaluating model explainability, detecting bias, and verifying compliance.',
    careerRoles: ['IT Auditor', 'Internal Audit Director', 'AI Model Auditor', 'Fairness Engineer'],
    connectedTo: ['crisc'],
    connectionReason: 'Bridges general IT risk control auditing into specialized algorithmic testing and bias detection.'
  }
];
