export const RASHI_LIST = [
  {
    id: "aries",
    vedicName: "Mesha (मेष)",
    englishName: "Aries",
    dates: "Mar 21 - Apr 19",
    symbol: "♈",
    animal: "Ram",
    element: "Fire",
    modality: "Movable (Chara)",
    ruler: "Mars (Mangal)",
    gemstone: "Red Coral & Diamond",
    luckyNumbers: [1, 8, 9],
    luckyColors: ["Crimson Red", "Scarlet", "Golden Yellow"],
    mantra: "Om Kram Kreem Kroum Sah Bhaumaya Namah",
    affirmation: "I am courageously stepping into my authentic power and leading with strength.",
    overview: "Pioneering, dynamic, and passionate. Mesha individuals possess an innate fire that drives them to lead, initiate, and conquer obstacles with fearless determination.",
    strengths: ["Bold Leadership", "Fearless Initiative", "High Energy", "Unwavering Honesty", "Passionate Focus"],
    weaknesses: ["Impatience", "Impulsiveness", "Short Temper", "Risk-taking without foresight"],
    loveBehavior: "In relationships, Aries is intensely romantic, passionate, and direct. They love the excitement of the chase and appreciate partners who respect their independent spirit.",
    careerBehavior: "Thrives in leadership, entrepreneurship, athletics, defense services, engineering, and fast-paced environments where quick action is required.",
    healthFocus: "Head, brain, eyes, and blood pressure. Benefits from intense workouts, meditation to calm the mind, and adequate hydration.",
    financialTraits: "Generous and quick to invest. Needs to practice cautious budgeting to avoid impulse spending.",
    compatibleSigns: ["Leo", "Sagittarius", "Gemini", "Aquarius"]
  },
  {
    id: "taurus",
    vedicName: "Vrishabha (वृषभ)",
    englishName: "Taurus",
    dates: "Apr 20 - May 20",
    symbol: "♉",
    animal: "Bull",
    element: "Earth",
    modality: "Fixed (Sthira)",
    ruler: "Venus (Shukra)",
    gemstone: "Diamond & Emerald",
    luckyNumbers: [2, 6, 7],
    luckyColors: ["Rose Pink", "Emerald Green", "White"],
    mantra: "Om Dram Dreem Droum Sah Shukraya Namah",
    affirmation: "I cultivate abundance, inner stability, and lasting joy in all areas of life.",
    overview: "Grounded, patient, and sensual. Vrishabha is ruled by Venus, giving them an appreciation for beauty, luxury, stability, and enduring loyalty.",
    strengths: ["Unshakable Loyalty", "Practical Wisdom", "Sensual Appreciation", "Reliability", "Determination"],
    weaknesses: ["Stubbornness", "Resistance to Change", "Possessiveness", "Over-indulgence"],
    loveBehavior: "Deeply committed, affectionate, and steadfast. Taurus builds secure, loving foundations and demonstrates love through practical care and quality time.",
    careerBehavior: "Excels in finance, banking, luxury goods, arts, architecture, real estate, and culinary domains requiring steady craftsmanship.",
    healthFocus: "Throat, neck, vocal cords, and thyroid gland. Singing, yoga neck stretches, and balanced diets support their stamina.",
    financialTraits: "Astute money builder. Prefers long-term investments, real estate, and secure savings over high-risk gambles.",
    compatibleSigns: ["Virgo", "Capricorn", "Cancer", "Scorpio"]
  },
  {
    id: "gemini",
    vedicName: "Mithuna (मिथुन)",
    englishName: "Gemini",
    dates: "May 21 - Jun 20",
    symbol: "♊",
    animal: "Twins",
    element: "Air",
    modality: "Dual (Dwiswabhava)",
    ruler: "Mercury (Budha)",
    gemstone: "Emerald & Peridot",
    luckyNumbers: [3, 5, 6],
    luckyColors: ["Light Green", "Yellow", "Sky Blue"],
    mantra: "Om Bram Breem Broum Sah Budhaya Namah",
    affirmation: "My mind is clear, versatile, and open to endless wisdom and joy.",
    overview: "Intellectual, communicative, and lively. Mithuna possesses a sharp intellect and insatiable curiosity, effortlessly adapting to new ideas and connections.",
    strengths: ["Quick Wit", "Excellent Communication", "Adaptability", "Multi-talented", "Charming Charm"],
    weaknesses: ["Restlessness", "Indecisiveness", "Superficial Interest", "Anxiety from Overthinking"],
    loveBehavior: "Needs mental stimulation and engaging conversation. Loves witty banter, intellectual alignment, and partner adventures.",
    careerBehavior: "Outstanding in journalism, writing, public relations, software development, marketing, sales, and teaching.",
    healthFocus: "Nervous system, lungs, shoulders, and hands. Breathing exercises (Pranayama) and digital detoxes keep them balanced.",
    financialTraits: "Flexible with money, often maintaining multiple income streams. Benefits from structured wealth management plans.",
    compatibleSigns: ["Libra", "Aquarius", "Aries", "Leo"]
  },
  {
    id: "cancer",
    vedicName: "Karka (कर्क)",
    englishName: "Cancer",
    dates: "Jun 21 - Jul 22",
    symbol: "♋",
    animal: "Crab",
    element: "Water",
    modality: "Movable (Chara)",
    ruler: "Moon (Chandra)",
    gemstone: "Pearl & Moonstone",
    luckyNumbers: [2, 4, 7],
    luckyColors: ["Silver White", "Sea Green", "Cream"],
    mantra: "Om Shram Shreem Shroum Sah Chandraya Namah",
    affirmation: "I honor my deep intuition and nurture loving, protective energy around me.",
    overview: "Intuitive, empathetic, and nurturing. Karka individuals are governed by the Moon, making them deeply sensitive, fiercely protective of loved ones, and spiritually receptive.",
    strengths: ["Profound Empathy", "Protective Instinct", "Strong Intuition", "Loyalty", "Creative Imagination"],
    weaknesses: ["Mood Swings", "Over-defensiveness", "Holding onto the Past", "Emotional Dependence"],
    loveBehavior: "Seeks profound emotional connection, emotional security, and a cozy home life. Extremely devoted and intuitive to their partner's unspoken needs.",
    careerBehavior: "Thrives in caregiving, medicine, counseling, hospitality, interior design, psychology, and maritime industries.",
    healthFocus: "Chest, stomach, digestive tract, and emotional health. Warm, comforting meals and ocean/water relaxation are healing.",
    financialTraits: "Naturally thrifty and security-minded. Prioritizes home ownership and family emergency funds.",
    compatibleSigns: ["Scorpio", "Pisces", "Taurus", "Virgo"]
  },
  {
    id: "leo",
    vedicName: "Simha (सिंह)",
    englishName: "Leo",
    dates: "Jul 23 - Aug 22",
    symbol: "♌",
    animal: "Lion",
    element: "Fire",
    modality: "Fixed (Sthira)",
    ruler: "Sun (Surya)",
    gemstone: "Ruby & Amber",
    luckyNumbers: [1, 5, 9],
    luckyColors: ["Royal Gold", "Warm Orange", "Bright Yellow"],
    mantra: "Om Hram Hreem Hroum Sah Suryaya Namah",
    affirmation: "I shine my inner light warmly and inspire confidence in everyone I meet.",
    overview: "Regal, charismatic, and big-hearted. Simha is ruled by the Sun, embodying authority, creative warmth, generous spirit, and natural nobility.",
    strengths: ["Magnetic Leadership", "Unmatched Generosity", "Self-Confidence", "Creativity", "Loyal Warmth"],
    weaknesses: ["Ego & Pride", "Need for Validation", "Stubbornness", "Tendency to Dominate"],
    loveBehavior: "Dramatic, passionate, and fiercely devoted. Loves grand romantic gestures and demands mutual respect and admiration.",
    careerBehavior: "Shines in executive leadership, performing arts, politics, creative direction, luxury hospitality, and public speaking.",
    healthFocus: "Heart, spine, upper back, and vitality. Cardiovascular fitness and sunlit outdoor activity boost their aura.",
    financialTraits: "Loves luxury and high-quality investments. Generous with family and friends, but should track impulse luxury purchases.",
    compatibleSigns: ["Aries", "Sagittarius", "Gemini", "Libra"]
  },
  {
    id: "virgo",
    vedicName: "Kanya (कन्या)",
    englishName: "Virgo",
    dates: "Aug 23 - Sep 22",
    symbol: "♍",
    animal: "Virgin / Maiden",
    element: "Earth",
    modality: "Dual (Dwiswabhava)",
    ruler: "Mercury (Budha)",
    gemstone: "Emerald & Sapphire",
    luckyNumbers: [5, 6, 8],
    luckyColors: ["Forest Green", "Beige", "Navy Blue"],
    mantra: "Om Bram Breem Broum Sah Budhaya Namah",
    affirmation: "I create order, purity, and purpose in every endeavor I undertake.",
    overview: "Analytical, precise, and dedicated. Kanya possesses an analytical mind tuned to perfection, practical problem solving, and selfless service.",
    strengths: ["Meticulous Precision", "Analytical Mind", "Practical Helpfulness", "High Standards", "Reliability"],
    weaknesses: ["Over-criticism", "Perfectionist Stress", "Worrying", "Excessive Modesty"],
    loveBehavior: "Demonstrates love through practical care, helpfulness, and quiet devotion. Values sincerity, tidiness, and intellectual compatibility.",
    careerBehavior: "Excels in data analysis, healthcare, research, accounting, editorial work, engineering, and quality management.",
    healthFocus: "Digestive system, intestines, and nervous system. Organic diets, mindful digestion, and nature walks keep them healthy.",
    financialTraits: "Disciplined saver and meticulous planner. Keeps detailed records and shuns reckless financial bets.",
    compatibleSigns: ["Taurus", "Capricorn", "Cancer", "Scorpio"]
  },
  {
    id: "libra",
    vedicName: "Tula (तुला)",
    englishName: "Libra",
    dates: "Sep 23 - Oct 22",
    symbol: "♎",
    animal: "Balance Scales",
    element: "Air",
    modality: "Movable (Chara)",
    ruler: "Venus (Shukra)",
    gemstone: "Diamond & Opal",
    luckyNumbers: [2, 6, 7],
    luckyColors: ["Pastel Blue", "Soft Pink", "Ivory"],
    mantra: "Om Dram Dreem Droum Sah Shukraya Namah",
    affirmation: "I bring harmony, justice, and elegant balance into my inner and outer world.",
    overview: "Harmonious, diplomatic, and artistic. Tula is represented by the scales of justice, seeking beauty, fairness, refined partnership, and peace.",
    strengths: ["Diplomatic Skill", "Aesthetic Taste", "Fair-mindedness", "Social Charm", "Peace-building"],
    weaknesses: ["Indecisiveness", "Conflict Avoidance", "Superficiality", "People-pleasing"],
    loveBehavior: "Natural romantic who thrives in equal, harmonious partnerships. Values beauty, gentle communication, and shared art.",
    careerBehavior: "Outstanding in law, diplomacy, fashion design, public relations, mediation, arts, and human resources.",
    healthFocus: "Kidneys, lower back, and skin. Hydration, balanced posture, and peaceful acoustic environments nourish them.",
    financialTraits: "Values financial balance. Likes spending on aesthetics and experiences, but benefits from automated investment schedules.",
    compatibleSigns: ["Gemini", "Aquarius", "Leo", "Sagittarius"]
  },
  {
    id: "scorpio",
    vedicName: "Vrishchika (वृश्चिक)",
    englishName: "Scorpio",
    dates: "Oct 23 - Nov 21",
    symbol: "♏",
    animal: "Scorpion",
    element: "Water",
    modality: "Fixed (Sthira)",
    ruler: "Mars & Pluto (Mangal/Ketu)",
    gemstone: "Red Coral & Topaz",
    luckyNumbers: [3, 4, 9],
    luckyColors: ["Maroon", "Deep Black", "Burgundy"],
    mantra: "Om Kram Kreem Kroum Sah Bhaumaya Namah",
    affirmation: "I embrace powerful transformation, releasing what no longer serves my highest good.",
    overview: "Mystical, intense, and transformative. Vrishchika possesses profound emotional depth, piercing intuition, and magnetic personal power.",
    strengths: ["Unwavering Focus", "Intuitive Depth", "Resilience", "Strategic Intelligence", "Loyalty"],
    weaknesses: ["Jealousy", "Secretiveness", "Grudges", "All-or-Nothing Intensity"],
    loveBehavior: "Intensely emotional, soulful, and protective. Demands absolute honesty and total spiritual/emotional commitment.",
    careerBehavior: "Excels in research, investigative journalism, surgery, psychology, crisis management, metallurgy, and occult sciences.",
    healthFocus: "Reproductive organs, excretory system, and inner vitality. Detoxification regimens and deep emotional release exercises help.",
    financialTraits: "Secretive and strategic about wealth. Excellent at managing joint finances, investments, and turnaround assets.",
    compatibleSigns: ["Cancer", "Pisces", "Virgo", "Taurus"]
  },
  {
    id: "sagittarius",
    vedicName: "Dhanu (धनु)",
    englishName: "Sagittarius",
    dates: "Nov 22 - Dec 21",
    symbol: "♐",
    animal: "Centaur Archer",
    element: "Fire",
    modality: "Dual (Dwiswabhava)",
    ruler: "Jupiter (Guru)",
    gemstone: "Yellow Sapphire & Topaz",
    luckyNumbers: [3, 5, 9],
    luckyColors: ["Royal Purple", "Saffron Yellow", "Gold"],
    mantra: "Om Gram Greem Groum Sah Gurave Namah",
    affirmation: "My wisdom expands constantly as I explore truth, freedom, and higher consciousness.",
    overview: "Philosophical, adventurous, and optimistic. Dhanu is guided by Jupiter, seeking ultimate truth, spiritual expansion, travel, and wisdom.",
    strengths: ["Boundless Optimism", "Philosophical Mind", "Love for Truth", "Generous Spirit", "Adventuresome"],
    weaknesses: ["Bluntness", "Over-promising", "Restlessness", "Tactlessness"],
    loveBehavior: "Fun-loving, direct, and freedom-respecting. Seeks an adventurous partner who shares their enthusiasm for philosophy and exploration.",
    careerBehavior: "Thrives in higher education, publishing, philosophy, international law, travel, theology, and mentorship.",
    healthFocus: "Hips, thighs, liver, and arterial system. Outdoor hiking, archery, and moderation in heavy food protect their liver.",
    financialTraits: "Optimistic investor. Needs to beware of over-confidence; balanced diversification yields great prosperity.",
    compatibleSigns: ["Aries", "Leo", "Libra", "Aquarius"]
  },
  {
    id: "capricorn",
    vedicName: "Makara (मकर)",
    englishName: "Capricorn",
    dates: "Dec 22 - Jan 19",
    symbol: "♑",
    animal: "Sea-Goat",
    element: "Earth",
    modality: "Movable (Chara)",
    ruler: "Saturn (Shani)",
    gemstone: "Blue Sapphire & Garnet",
    luckyNumbers: [4, 8, 13],
    luckyColors: ["Charcoal Grey", "Dark Blue", "Brown"],
    mantra: "Om Pram Preem Proum Sah Shanaishcharaya Namah",
    affirmation: "Through discipline and perseverance, I build an enduring legacy of excellence.",
    overview: "Ambitious, disciplined, and resilient. Makara is ruled by Saturn, mastering patience, structure, self-control, and steady ascent to mountain peaks.",
    strengths: ["Steadfast Discipline", "Strategic Ambition", "Patience", "High Responsibility", "Pragmatism"],
    weaknesses: ["Pessimism", "Workaholism", "Rigidity", "Emotional Distance"],
    loveBehavior: "Takes love seriously and seeks stability. Slow to open up, but once committed, remains steadfast for life.",
    careerBehavior: "Outstanding in corporate governance, engineering, government leadership, real estate, civil engineering, and administration.",
    healthFocus: "Bones, joints, knees, teeth, and skin. Calcium nutrition, strength training, and joint mobility exercises keep them robust.",
    financialTraits: "Master of long-term wealth accumulation. Conservative, disciplined saver who builds lasting assets step by step.",
    compatibleSigns: ["Taurus", "Virgo", "Scorpio", "Pisces"]
  },
  {
    id: "aquarius",
    vedicName: "Kumbha (कुंभ)",
    englishName: "Aquarius",
    dates: "Jan 20 - Feb 18",
    symbol: "♒",
    animal: "Water Bearer",
    element: "Air",
    modality: "Fixed (Sthira)",
    ruler: "Saturn & Uranus (Shani/Rahu)",
    gemstone: "Blue Sapphire & Amethyst",
    luckyNumbers: [4, 7, 11],
    luckyColors: ["Electric Blue", "Ultramarine", "Silver"],
    mantra: "Om Pram Preem Proum Sah Shanaishcharaya Namah",
    affirmation: "I contribute innovative, humanitarian ideas to create a brighter future for all.",
    overview: "Visionary, humanitarian, and original. Kumbha pours knowledge and innovative progress onto humanity, unburdened by conventional limits.",
    strengths: ["Innovative Thinking", "Humanitarian Heart", "Intellectual Independence", "Originality", "Loyal Friendship"],
    weaknesses: ["Detachment", "Unpredictability", "Stubborn Dogma", "Rebellion without cause"],
    loveBehavior: "Values intellectual equality and freedom. Forms deep friendships before romance and appreciates open-minded partners.",
    careerBehavior: "Pioneers in technology, artificial intelligence, astronomy, social work, scientific research, aviation, and humanitarian causes.",
    healthFocus: "Shins, ankles, calves, and circulatory system. Aerobic workouts, circulation exercises, and group sports suit them best.",
    financialTraits: "Unconventional financial view. Often invests in futuristic tech, green energy, and decentralized systems.",
    compatibleSigns: ["Gemini", "Libra", "Aries", "Sagittarius"]
  },
  {
    id: "pisces",
    vedicName: "Meena (मीन)",
    englishName: "Pisces",
    dates: "Feb 19 - Mar 20",
    symbol: "♓",
    animal: "Two Fishes",
    element: "Water",
    modality: "Dual (Dwiswabhava)",
    ruler: "Jupiter & Neptune (Guru/Ketu)",
    gemstone: "Yellow Sapphire & Aquamarine",
    luckyNumbers: [3, 7, 12],
    luckyColors: ["Sea Foam Green", "Lavender", "Soft Yellow"],
    mantra: "Om Gram Greem Groum Sah Gurave Namah",
    affirmation: "I am connected to the infinite universe, radiating compassion, art, and divine peace.",
    overview: "Compassionate, mystical, and artistic. Meena is the final sign of the zodiac, embodying universal empathy, dreamlike imagination, and spiritual surrender.",
    strengths: ["Boundless Empathy", "Artistic Genius", "Spiritual Intuition", "Compassion", "Adaptability"],
    weaknesses: ["Escapism", "Over-sensitivity", "Difficulty with Boundaries", "Idealism"],
    loveBehavior: "Deeply romantic, soulful, and self-sacrificing. Seeks spiritual soulmates who cherish their sensitivity and imaginative world.",
    careerBehavior: "Excels in music, poetry, film production, holistic healing, marine biology, spiritual teaching, and psychology.",
    healthFocus: "Feet, lymphatic system, and immune response. Warm foot baths, yoga, swimming, and creative arts balance their energy.",
    financialTraits: "Intuitive with money, but needs practical boundaries to prevent over-giving or neglect of financial details.",
    compatibleSigns: ["Cancer", "Scorpio", "Taurus", "Capricorn"]
  }
];
